// City + month → avg air temp (°C), conditions, water temp (°C where applicable)
// Based on historical climate averages. Month: 1=Jan ... 12=Dec
// waterTemp: relevant for Swim, SwimRun, Triathlon. null = not applicable or unknown.

export interface WeatherInfo {
  temp: number;        // avg air temp °C
  condition: string;   // e.g. "Dry", "Humid", "Wet", "Hot & Humid", "Cool", "Cold"
  waterTemp: number | null; // avg water temp °C (sea/lake), null if unknown/N/A
}

// City-level monthly weather data
// Format: CITY_WEATHER[city][month] = WeatherInfo
export const CITY_WEATHER: Record<string, Record<number, WeatherInfo>> = {
  // ── INDIA ──
  "Chennai": {
    1: { temp: 24, condition: "Dry", waterTemp: 27 },
    2: { temp: 26, condition: "Dry", waterTemp: 27 },
    3: { temp: 29, condition: "Hot", waterTemp: 28 },
    4: { temp: 32, condition: "Hot", waterTemp: 29 },
    5: { temp: 34, condition: "Hot & Humid", waterTemp: 30 },
    6: { temp: 33, condition: "Wet", waterTemp: 30 },
    7: { temp: 31, condition: "Wet", waterTemp: 29 },
    8: { temp: 31, condition: "Wet", waterTemp: 29 },
    9: { temp: 30, condition: "Wet", waterTemp: 29 },
    10: { temp: 28, condition: "Wet", waterTemp: 28 },
    11: { temp: 25, condition: "Humid", waterTemp: 27 },
    12: { temp: 23, condition: "Dry", waterTemp: 27 },
  },
  "Mumbai": {
    1: { temp: 24, condition: "Dry", waterTemp: 25 },
    2: { temp: 25, condition: "Dry", waterTemp: 25 },
    3: { temp: 28, condition: "Hot", waterTemp: 26 },
    4: { temp: 30, condition: "Hot", waterTemp: 27 },
    5: { temp: 32, condition: "Hot & Humid", waterTemp: 28 },
    6: { temp: 30, condition: "Wet", waterTemp: 28 },
    7: { temp: 28, condition: "Wet", waterTemp: 27 },
    8: { temp: 28, condition: "Wet", waterTemp: 27 },
    9: { temp: 28, condition: "Wet", waterTemp: 27 },
    10: { temp: 29, condition: "Humid", waterTemp: 27 },
    11: { temp: 27, condition: "Dry", waterTemp: 26 },
    12: { temp: 24, condition: "Dry", waterTemp: 25 },
  },
  "Goa": {
    1: { temp: 24, condition: "Dry", waterTemp: 27 },
    2: { temp: 25, condition: "Dry", waterTemp: 27 },
    3: { temp: 28, condition: "Hot", waterTemp: 28 },
    4: { temp: 31, condition: "Hot", waterTemp: 29 },
    5: { temp: 32, condition: "Hot & Humid", waterTemp: 30 },
    6: { temp: 29, condition: "Wet", waterTemp: 29 },
    7: { temp: 28, condition: "Wet", waterTemp: 28 },
    8: { temp: 28, condition: "Wet", waterTemp: 28 },
    9: { temp: 28, condition: "Wet", waterTemp: 28 },
    10: { temp: 28, condition: "Humid", waterTemp: 28 },
    11: { temp: 26, condition: "Dry", waterTemp: 27 },
    12: { temp: 24, condition: "Dry", waterTemp: 27 },
  },
  "Bengaluru": {
    1: { temp: 20, condition: "Dry", waterTemp: null },
    2: { temp: 22, condition: "Dry", waterTemp: null },
    3: { temp: 25, condition: "Hot", waterTemp: null },
    4: { temp: 27, condition: "Hot", waterTemp: null },
    5: { temp: 26, condition: "Humid", waterTemp: null },
    6: { temp: 23, condition: "Wet", waterTemp: null },
    7: { temp: 22, condition: "Wet", waterTemp: null },
    8: { temp: 22, condition: "Wet", waterTemp: null },
    9: { temp: 22, condition: "Wet", waterTemp: null },
    10: { temp: 22, condition: "Wet", waterTemp: null },
    11: { temp: 20, condition: "Dry", waterTemp: null },
    12: { temp: 19, condition: "Dry", waterTemp: null },
  },
  "New Delhi": {
    1: { temp: 7, condition: "Cold", waterTemp: null },
    2: { temp: 10, condition: "Cool", waterTemp: null },
    3: { temp: 16, condition: "Dry", waterTemp: null },
    4: { temp: 23, condition: "Hot", waterTemp: null },
    5: { temp: 29, condition: "Hot", waterTemp: null },
    6: { temp: 33, condition: "Hot", waterTemp: null },
    7: { temp: 31, condition: "Wet", waterTemp: null },
    8: { temp: 30, condition: "Wet", waterTemp: null },
    9: { temp: 28, condition: "Wet", waterTemp: null },
    10: { temp: 22, condition: "Dry", waterTemp: null },
    11: { temp: 14, condition: "Cool", waterTemp: null },
    12: { temp: 8, condition: "Cold", waterTemp: null },
  },
  "Kolkata": {
    1: { temp: 18, condition: "Dry", waterTemp: null },
    2: { temp: 21, condition: "Dry", waterTemp: null },
    3: { temp: 26, condition: "Hot", waterTemp: null },
    4: { temp: 30, condition: "Hot", waterTemp: null },
    5: { temp: 32, condition: "Hot & Humid", waterTemp: null },
    6: { temp: 31, condition: "Wet", waterTemp: null },
    7: { temp: 30, condition: "Wet", waterTemp: null },
    8: { temp: 30, condition: "Wet", waterTemp: null },
    9: { temp: 30, condition: "Wet", waterTemp: null },
    10: { temp: 28, condition: "Humid", waterTemp: null },
    11: { temp: 23, condition: "Dry", waterTemp: null },
    12: { temp: 18, condition: "Dry", waterTemp: null },
  },
  "Kevadia": {
    1: { temp: 18, condition: "Dry", waterTemp: null },
    2: { temp: 21, condition: "Dry", waterTemp: null },
    3: { temp: 26, condition: "Hot", waterTemp: null },
    4: { temp: 31, condition: "Hot", waterTemp: null },
    5: { temp: 34, condition: "Hot", waterTemp: null },
    6: { temp: 33, condition: "Wet", waterTemp: null },
    7: { temp: 29, condition: "Wet", waterTemp: null },
    8: { temp: 28, condition: "Wet", waterTemp: null },
    9: { temp: 29, condition: "Wet", waterTemp: null },
    10: { temp: 28, condition: "Dry", waterTemp: null },
    11: { temp: 23, condition: "Dry", waterTemp: null },
    12: { temp: 18, condition: "Dry", waterTemp: null },
  },
  // ── JAPAN ──
  "Tokyo": {
    1: { temp: 5, condition: "Cold & Dry", waterTemp: 16 },
    2: { temp: 6, condition: "Cold & Dry", waterTemp: 15 },
    3: { temp: 10, condition: "Cool", waterTemp: 16 },
    4: { temp: 15, condition: "Mild", waterTemp: 17 },
    5: { temp: 20, condition: "Mild", waterTemp: 19 },
    6: { temp: 23, condition: "Humid", waterTemp: 21 },
    7: { temp: 27, condition: "Hot & Humid", waterTemp: 24 },
    8: { temp: 29, condition: "Hot & Humid", waterTemp: 26 },
    9: { temp: 25, condition: "Humid", waterTemp: 25 },
    10: { temp: 18, condition: "Mild", waterTemp: 23 },
    11: { temp: 12, condition: "Cool", waterTemp: 20 },
    12: { temp: 7, condition: "Cold", waterTemp: 18 },
  },
  "Osaka": {
    1: { temp: 5, condition: "Cold", waterTemp: null },
    2: { temp: 6, condition: "Cold", waterTemp: null },
    3: { temp: 10, condition: "Cool", waterTemp: null },
    4: { temp: 16, condition: "Mild", waterTemp: null },
    5: { temp: 21, condition: "Mild", waterTemp: null },
    6: { temp: 25, condition: "Humid", waterTemp: null },
    7: { temp: 29, condition: "Hot & Humid", waterTemp: null },
    8: { temp: 31, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 26, condition: "Humid", waterTemp: null },
    10: { temp: 19, condition: "Mild", waterTemp: null },
    11: { temp: 13, condition: "Cool", waterTemp: null },
    12: { temp: 7, condition: "Cold", waterTemp: null },
  },
  "Kyoto": {
    1: { temp: 4, condition: "Cold", waterTemp: null },
    2: { temp: 5, condition: "Cold", waterTemp: null },
    3: { temp: 9, condition: "Cool", waterTemp: null },
    4: { temp: 16, condition: "Mild", waterTemp: null },
    5: { temp: 21, condition: "Mild", waterTemp: null },
    6: { temp: 25, condition: "Humid", waterTemp: null },
    7: { temp: 29, condition: "Hot & Humid", waterTemp: null },
    8: { temp: 31, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 26, condition: "Humid", waterTemp: null },
    10: { temp: 19, condition: "Mild", waterTemp: null },
    11: { temp: 12, condition: "Cool", waterTemp: null },
    12: { temp: 6, condition: "Cold", waterTemp: null },
  },
  "Nagoya": {
    1: { temp: 4, condition: "Cold", waterTemp: null },
    2: { temp: 5, condition: "Cold", waterTemp: null },
    3: { temp: 9, condition: "Cool", waterTemp: null },
    4: { temp: 16, condition: "Mild", waterTemp: null },
    5: { temp: 21, condition: "Mild", waterTemp: null },
    6: { temp: 25, condition: "Humid", waterTemp: null },
    7: { temp: 29, condition: "Hot & Humid", waterTemp: null },
    8: { temp: 31, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 26, condition: "Humid", waterTemp: null },
    10: { temp: 19, condition: "Mild", waterTemp: null },
    11: { temp: 12, condition: "Cool", waterTemp: null },
    12: { temp: 6, condition: "Cold", waterTemp: null },
  },
  // ── THAILAND ──
  "Bangkok": {
    1: { temp: 27, condition: "Dry", waterTemp: null },
    2: { temp: 29, condition: "Dry", waterTemp: null },
    3: { temp: 31, condition: "Hot", waterTemp: null },
    4: { temp: 33, condition: "Hot", waterTemp: null },
    5: { temp: 31, condition: "Wet", waterTemp: null },
    6: { temp: 30, condition: "Wet", waterTemp: null },
    7: { temp: 29, condition: "Wet", waterTemp: null },
    8: { temp: 29, condition: "Wet", waterTemp: null },
    9: { temp: 29, condition: "Wet", waterTemp: null },
    10: { temp: 28, condition: "Wet", waterTemp: null },
    11: { temp: 27, condition: "Dry", waterTemp: null },
    12: { temp: 26, condition: "Dry", waterTemp: null },
  },
  "Phuket": {
    1: { temp: 27, condition: "Dry", waterTemp: 28 },
    2: { temp: 28, condition: "Dry", waterTemp: 28 },
    3: { temp: 29, condition: "Dry", waterTemp: 29 },
    4: { temp: 30, condition: "Hot", waterTemp: 30 },
    5: { temp: 29, condition: "Wet", waterTemp: 29 },
    6: { temp: 28, condition: "Wet", waterTemp: 29 },
    7: { temp: 28, condition: "Wet", waterTemp: 28 },
    8: { temp: 28, condition: "Wet", waterTemp: 28 },
    9: { temp: 27, condition: "Wet", waterTemp: 28 },
    10: { temp: 27, condition: "Wet", waterTemp: 28 },
    11: { temp: 27, condition: "Dry", waterTemp: 28 },
    12: { temp: 27, condition: "Dry", waterTemp: 28 },
  },
  "Chiang Mai": {
    1: { temp: 18, condition: "Dry & Cool", waterTemp: null },
    2: { temp: 21, condition: "Dry", waterTemp: null },
    3: { temp: 26, condition: "Hot", waterTemp: null },
    4: { temp: 30, condition: "Hot", waterTemp: null },
    5: { temp: 28, condition: "Wet", waterTemp: null },
    6: { temp: 27, condition: "Wet", waterTemp: null },
    7: { temp: 27, condition: "Wet", waterTemp: null },
    8: { temp: 27, condition: "Wet", waterTemp: null },
    9: { temp: 26, condition: "Wet", waterTemp: null },
    10: { temp: 25, condition: "Humid", waterTemp: null },
    11: { temp: 22, condition: "Dry", waterTemp: null },
    12: { temp: 18, condition: "Dry & Cool", waterTemp: null },
  },
  "Koh Samui": {
    1: { temp: 26, condition: "Dry", waterTemp: 27 },
    2: { temp: 27, condition: "Dry", waterTemp: 27 },
    3: { temp: 28, condition: "Dry", waterTemp: 28 },
    4: { temp: 29, condition: "Hot", waterTemp: 29 },
    5: { temp: 29, condition: "Wet", waterTemp: 29 },
    6: { temp: 29, condition: "Wet", waterTemp: 29 },
    7: { temp: 28, condition: "Wet", waterTemp: 29 },
    8: { temp: 28, condition: "Wet", waterTemp: 29 },
    9: { temp: 27, condition: "Wet", waterTemp: 28 },
    10: { temp: 26, condition: "Wet", waterTemp: 27 },
    11: { temp: 25, condition: "Wet", waterTemp: 27 },
    12: { temp: 25, condition: "Humid", waterTemp: 27 },
  },
  // ── VIETNAM ──
  "Ho Chi Minh City": {
    1: { temp: 27, condition: "Dry", waterTemp: null },
    2: { temp: 28, condition: "Dry", waterTemp: null },
    3: { temp: 30, condition: "Hot", waterTemp: null },
    4: { temp: 31, condition: "Hot", waterTemp: null },
    5: { temp: 29, condition: "Wet", waterTemp: null },
    6: { temp: 28, condition: "Wet", waterTemp: null },
    7: { temp: 27, condition: "Wet", waterTemp: null },
    8: { temp: 27, condition: "Wet", waterTemp: null },
    9: { temp: 27, condition: "Wet", waterTemp: null },
    10: { temp: 27, condition: "Wet", waterTemp: null },
    11: { temp: 27, condition: "Humid", waterTemp: null },
    12: { temp: 26, condition: "Dry", waterTemp: null },
  },
  "Hanoi": {
    1: { temp: 17, condition: "Cool & Drizzly", waterTemp: null },
    2: { temp: 18, condition: "Cool & Drizzly", waterTemp: null },
    3: { temp: 21, condition: "Humid", waterTemp: null },
    4: { temp: 25, condition: "Humid", waterTemp: null },
    5: { temp: 29, condition: "Hot & Humid", waterTemp: null },
    6: { temp: 31, condition: "Hot & Wet", waterTemp: null },
    7: { temp: 31, condition: "Hot & Wet", waterTemp: null },
    8: { temp: 30, condition: "Hot & Wet", waterTemp: null },
    9: { temp: 29, condition: "Wet", waterTemp: null },
    10: { temp: 26, condition: "Dry", waterTemp: null },
    11: { temp: 22, condition: "Cool", waterTemp: null },
    12: { temp: 18, condition: "Cool", waterTemp: null },
  },
  "Sapa": {
    1: { temp: 10, condition: "Cold & Misty", waterTemp: null },
    2: { temp: 11, condition: "Cold & Misty", waterTemp: null },
    3: { temp: 14, condition: "Cool & Misty", waterTemp: null },
    4: { temp: 18, condition: "Mild", waterTemp: null },
    5: { temp: 20, condition: "Mild & Wet", waterTemp: null },
    6: { temp: 21, condition: "Wet", waterTemp: null },
    7: { temp: 21, condition: "Wet", waterTemp: null },
    8: { temp: 21, condition: "Wet", waterTemp: null },
    9: { temp: 19, condition: "Wet", waterTemp: null },
    10: { temp: 16, condition: "Cool", waterTemp: null },
    11: { temp: 12, condition: "Cool", waterTemp: null },
    12: { temp: 9, condition: "Cold", waterTemp: null },
  },
  "Da Nang": {
    1: { temp: 21, condition: "Cool & Wet", waterTemp: 24 },
    2: { temp: 22, condition: "Cool", waterTemp: 24 },
    3: { temp: 24, condition: "Mild", waterTemp: 25 },
    4: { temp: 27, condition: "Dry", waterTemp: 26 },
    5: { temp: 30, condition: "Hot", waterTemp: 27 },
    6: { temp: 31, condition: "Hot", waterTemp: 28 },
    7: { temp: 31, condition: "Hot", waterTemp: 28 },
    8: { temp: 31, condition: "Hot & Wet", waterTemp: 29 },
    9: { temp: 29, condition: "Wet", waterTemp: 28 },
    10: { temp: 26, condition: "Wet", waterTemp: 27 },
    11: { temp: 23, condition: "Wet", waterTemp: 25 },
    12: { temp: 21, condition: "Cool & Wet", waterTemp: 24 },
  },
  // ── PHILIPPINES ──
  "Manila": {
    1: { temp: 26, condition: "Dry", waterTemp: 27 },
    2: { temp: 27, condition: "Dry", waterTemp: 27 },
    3: { temp: 29, condition: "Hot", waterTemp: 28 },
    4: { temp: 31, condition: "Hot", waterTemp: 29 },
    5: { temp: 31, condition: "Hot & Wet", waterTemp: 30 },
    6: { temp: 29, condition: "Wet", waterTemp: 30 },
    7: { temp: 28, condition: "Wet", waterTemp: 29 },
    8: { temp: 28, condition: "Wet", waterTemp: 29 },
    9: { temp: 28, condition: "Wet", waterTemp: 29 },
    10: { temp: 28, condition: "Wet", waterTemp: 29 },
    11: { temp: 27, condition: "Humid", waterTemp: 28 },
    12: { temp: 26, condition: "Dry", waterTemp: 27 },
  },
  "Subic Bay": {
    1: { temp: 25, condition: "Dry", waterTemp: 27 },
    2: { temp: 26, condition: "Dry", waterTemp: 27 },
    3: { temp: 28, condition: "Hot", waterTemp: 28 },
    4: { temp: 30, condition: "Hot", waterTemp: 29 },
    5: { temp: 30, condition: "Hot & Wet", waterTemp: 30 },
    6: { temp: 28, condition: "Wet", waterTemp: 29 },
    7: { temp: 27, condition: "Wet", waterTemp: 29 },
    8: { temp: 27, condition: "Wet", waterTemp: 29 },
    9: { temp: 27, condition: "Wet", waterTemp: 29 },
    10: { temp: 27, condition: "Wet", waterTemp: 28 },
    11: { temp: 26, condition: "Humid", waterTemp: 27 },
    12: { temp: 25, condition: "Dry", waterTemp: 27 },
  },
  "Mactan": {
    1: { temp: 27, condition: "Dry", waterTemp: 27 },
    2: { temp: 28, condition: "Dry", waterTemp: 27 },
    3: { temp: 29, condition: "Hot", waterTemp: 28 },
    4: { temp: 31, condition: "Hot", waterTemp: 29 },
    5: { temp: 31, condition: "Hot & Wet", waterTemp: 30 },
    6: { temp: 29, condition: "Wet", waterTemp: 29 },
    7: { temp: 28, condition: "Wet", waterTemp: 29 },
    8: { temp: 28, condition: "Wet", waterTemp: 29 },
    9: { temp: 28, condition: "Wet", waterTemp: 29 },
    10: { temp: 28, condition: "Wet", waterTemp: 28 },
    11: { temp: 27, condition: "Humid", waterTemp: 28 },
    12: { temp: 27, condition: "Dry", waterTemp: 27 },
  },
  // ── INDONESIA ──
  "Bali": {
    1: { temp: 27, condition: "Wet", waterTemp: 28 },
    2: { temp: 27, condition: "Wet", waterTemp: 28 },
    3: { temp: 28, condition: "Wet", waterTemp: 28 },
    4: { temp: 28, condition: "Humid", waterTemp: 29 },
    5: { temp: 27, condition: "Dry", waterTemp: 28 },
    6: { temp: 26, condition: "Dry & Cool", waterTemp: 27 },
    7: { temp: 25, condition: "Dry & Cool", waterTemp: 26 },
    8: { temp: 25, condition: "Dry & Cool", waterTemp: 26 },
    9: { temp: 26, condition: "Dry", waterTemp: 27 },
    10: { temp: 27, condition: "Dry", waterTemp: 28 },
    11: { temp: 27, condition: "Wet", waterTemp: 28 },
    12: { temp: 27, condition: "Wet", waterTemp: 28 },
  },
  "Lombok": {
    1: { temp: 27, condition: "Wet", waterTemp: 28 },
    2: { temp: 27, condition: "Wet", waterTemp: 28 },
    3: { temp: 27, condition: "Wet", waterTemp: 28 },
    4: { temp: 28, condition: "Humid", waterTemp: 29 },
    5: { temp: 27, condition: "Dry", waterTemp: 28 },
    6: { temp: 25, condition: "Dry & Cool", waterTemp: 27 },
    7: { temp: 24, condition: "Dry & Cool", waterTemp: 26 },
    8: { temp: 24, condition: "Dry & Cool", waterTemp: 26 },
    9: { temp: 25, condition: "Dry", waterTemp: 27 },
    10: { temp: 27, condition: "Dry", waterTemp: 28 },
    11: { temp: 27, condition: "Wet", waterTemp: 28 },
    12: { temp: 27, condition: "Wet", waterTemp: 28 },
  },
  "Jakarta": {
    1: { temp: 27, condition: "Wet", waterTemp: null },
    2: { temp: 27, condition: "Wet", waterTemp: null },
    3: { temp: 28, condition: "Wet", waterTemp: null },
    4: { temp: 29, condition: "Humid", waterTemp: null },
    5: { temp: 29, condition: "Dry", waterTemp: null },
    6: { temp: 28, condition: "Dry", waterTemp: null },
    7: { temp: 28, condition: "Dry", waterTemp: null },
    8: { temp: 28, condition: "Dry", waterTemp: null },
    9: { temp: 29, condition: "Dry", waterTemp: null },
    10: { temp: 29, condition: "Wet", waterTemp: null },
    11: { temp: 28, condition: "Wet", waterTemp: null },
    12: { temp: 27, condition: "Wet", waterTemp: null },
  },
  "Nusa Lembongan": {
    1: { temp: 27, condition: "Wet", waterTemp: 28 },
    2: { temp: 27, condition: "Wet", waterTemp: 28 },
    3: { temp: 28, condition: "Wet", waterTemp: 28 },
    4: { temp: 29, condition: "Humid", waterTemp: 29 },
    5: { temp: 28, condition: "Dry", waterTemp: 28 },
    6: { temp: 26, condition: "Dry & Cool", waterTemp: 27 },
    7: { temp: 25, condition: "Dry & Cool", waterTemp: 26 },
    8: { temp: 25, condition: "Dry & Cool", waterTemp: 26 },
    9: { temp: 26, condition: "Dry", waterTemp: 27 },
    10: { temp: 27, condition: "Dry", waterTemp: 28 },
    11: { temp: 27, condition: "Wet", waterTemp: 28 },
    12: { temp: 27, condition: "Wet", waterTemp: 28 },
  },
  // ── MALAYSIA ──
  "Kuala Lumpur": {
    1: { temp: 28, condition: "Humid", waterTemp: null },
    2: { temp: 29, condition: "Humid", waterTemp: null },
    3: { temp: 30, condition: "Hot & Humid", waterTemp: null },
    4: { temp: 30, condition: "Hot & Humid", waterTemp: null },
    5: { temp: 30, condition: "Wet", waterTemp: null },
    6: { temp: 29, condition: "Wet", waterTemp: null },
    7: { temp: 29, condition: "Wet", waterTemp: null },
    8: { temp: 29, condition: "Wet", waterTemp: null },
    9: { temp: 29, condition: "Wet", waterTemp: null },
    10: { temp: 29, condition: "Wet", waterTemp: null },
    11: { temp: 28, condition: "Wet", waterTemp: null },
    12: { temp: 28, condition: "Wet", waterTemp: null },
  },
  "Putrajaya": {
    1: { temp: 28, condition: "Humid", waterTemp: null },
    2: { temp: 29, condition: "Humid", waterTemp: null },
    3: { temp: 30, condition: "Hot & Humid", waterTemp: null },
    4: { temp: 30, condition: "Hot & Humid", waterTemp: null },
    5: { temp: 30, condition: "Wet", waterTemp: null },
    6: { temp: 29, condition: "Wet", waterTemp: null },
    7: { temp: 29, condition: "Wet", waterTemp: null },
    8: { temp: 29, condition: "Wet", waterTemp: null },
    9: { temp: 29, condition: "Wet", waterTemp: null },
    10: { temp: 29, condition: "Wet", waterTemp: null },
    11: { temp: 28, condition: "Wet", waterTemp: null },
    12: { temp: 28, condition: "Wet", waterTemp: null },
  },
  "Penang": {
    1: { temp: 27, condition: "Dry", waterTemp: 28 },
    2: { temp: 28, condition: "Dry", waterTemp: 28 },
    3: { temp: 29, condition: "Hot", waterTemp: 29 },
    4: { temp: 30, condition: "Hot", waterTemp: 29 },
    5: { temp: 29, condition: "Wet", waterTemp: 29 },
    6: { temp: 28, condition: "Wet", waterTemp: 29 },
    7: { temp: 28, condition: "Wet", waterTemp: 29 },
    8: { temp: 28, condition: "Wet", waterTemp: 29 },
    9: { temp: 28, condition: "Wet", waterTemp: 28 },
    10: { temp: 28, condition: "Wet", waterTemp: 28 },
    11: { temp: 27, condition: "Wet", waterTemp: 28 },
    12: { temp: 27, condition: "Humid", waterTemp: 27 },
  },
  "Kota Kinabalu": {
    1: { temp: 27, condition: "Wet", waterTemp: 28 },
    2: { temp: 27, condition: "Wet", waterTemp: 28 },
    3: { temp: 28, condition: "Humid", waterTemp: 29 },
    4: { temp: 29, condition: "Hot", waterTemp: 29 },
    5: { temp: 29, condition: "Wet", waterTemp: 30 },
    6: { temp: 28, condition: "Wet", waterTemp: 29 },
    7: { temp: 28, condition: "Wet", waterTemp: 29 },
    8: { temp: 28, condition: "Wet", waterTemp: 29 },
    9: { temp: 28, condition: "Wet", waterTemp: 29 },
    10: { temp: 28, condition: "Wet", waterTemp: 28 },
    11: { temp: 27, condition: "Wet", waterTemp: 28 },
    12: { temp: 27, condition: "Wet", waterTemp: 28 },
  },
  // ── SINGAPORE ──
  "Singapore": {
    1: { temp: 27, condition: "Wet", waterTemp: 28 },
    2: { temp: 28, condition: "Dry", waterTemp: 28 },
    3: { temp: 28, condition: "Dry", waterTemp: 29 },
    4: { temp: 29, condition: "Dry", waterTemp: 29 },
    5: { temp: 29, condition: "Wet", waterTemp: 30 },
    6: { temp: 29, condition: "Wet", waterTemp: 30 },
    7: { temp: 28, condition: "Wet", waterTemp: 29 },
    8: { temp: 28, condition: "Wet", waterTemp: 29 },
    9: { temp: 28, condition: "Wet", waterTemp: 29 },
    10: { temp: 28, condition: "Wet", waterTemp: 29 },
    11: { temp: 27, condition: "Wet", waterTemp: 28 },
    12: { temp: 27, condition: "Wet", waterTemp: 28 },
  },
  // ── SOUTH KOREA ──
  "Seoul": {
    1: { temp: -2, condition: "Cold & Dry", waterTemp: null },
    2: { temp: 1, condition: "Cold", waterTemp: null },
    3: { temp: 7, condition: "Cool", waterTemp: null },
    4: { temp: 14, condition: "Mild", waterTemp: null },
    5: { temp: 20, condition: "Mild", waterTemp: null },
    6: { temp: 24, condition: "Humid", waterTemp: null },
    7: { temp: 27, condition: "Hot & Wet", waterTemp: null },
    8: { temp: 28, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 23, condition: "Mild", waterTemp: null },
    10: { temp: 16, condition: "Cool", waterTemp: null },
    11: { temp: 8, condition: "Cool", waterTemp: null },
    12: { temp: 1, condition: "Cold", waterTemp: null },
  },
  "Jeju Island": {
    1: { temp: 6, condition: "Cool", waterTemp: 17 },
    2: { temp: 7, condition: "Cool", waterTemp: 16 },
    3: { temp: 10, condition: "Mild", waterTemp: 17 },
    4: { temp: 15, condition: "Mild", waterTemp: 18 },
    5: { temp: 20, condition: "Mild", waterTemp: 20 },
    6: { temp: 23, condition: "Humid", waterTemp: 22 },
    7: { temp: 27, condition: "Hot & Wet", waterTemp: 25 },
    8: { temp: 28, condition: "Hot & Humid", waterTemp: 27 },
    9: { temp: 24, condition: "Mild", waterTemp: 26 },
    10: { temp: 18, condition: "Mild", waterTemp: 23 },
    11: { temp: 12, condition: "Cool", waterTemp: 20 },
    12: { temp: 7, condition: "Cool", waterTemp: 18 },
  },
  // ── CHINA ──
  "Shanghai": {
    1: { temp: 4, condition: "Cold", waterTemp: null },
    2: { temp: 6, condition: "Cold", waterTemp: null },
    3: { temp: 10, condition: "Cool", waterTemp: null },
    4: { temp: 16, condition: "Mild", waterTemp: null },
    5: { temp: 22, condition: "Mild", waterTemp: null },
    6: { temp: 26, condition: "Humid", waterTemp: null },
    7: { temp: 30, condition: "Hot & Humid", waterTemp: null },
    8: { temp: 30, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 25, condition: "Humid", waterTemp: null },
    10: { temp: 19, condition: "Mild", waterTemp: null },
    11: { temp: 12, condition: "Cool", waterTemp: null },
    12: { temp: 6, condition: "Cold", waterTemp: null },
  },
  "Beijing": {
    1: { temp: -2, condition: "Cold & Dry", waterTemp: null },
    2: { temp: 1, condition: "Cold", waterTemp: null },
    3: { temp: 8, condition: "Cool", waterTemp: null },
    4: { temp: 16, condition: "Mild", waterTemp: null },
    5: { temp: 22, condition: "Warm", waterTemp: null },
    6: { temp: 27, condition: "Hot", waterTemp: null },
    7: { temp: 29, condition: "Hot & Wet", waterTemp: null },
    8: { temp: 28, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 22, condition: "Mild", waterTemp: null },
    10: { temp: 14, condition: "Cool", waterTemp: null },
    11: { temp: 5, condition: "Cool", waterTemp: null },
    12: { temp: -1, condition: "Cold", waterTemp: null },
  },
  "Hong Kong": {
    1: { temp: 16, condition: "Cool", waterTemp: 20 },
    2: { temp: 17, condition: "Cool & Humid", waterTemp: 19 },
    3: { temp: 20, condition: "Humid", waterTemp: 20 },
    4: { temp: 24, condition: "Humid", waterTemp: 22 },
    5: { temp: 28, condition: "Hot & Wet", waterTemp: 25 },
    6: { temp: 30, condition: "Hot & Wet", waterTemp: 27 },
    7: { temp: 31, condition: "Hot & Wet", waterTemp: 28 },
    8: { temp: 31, condition: "Hot & Wet", waterTemp: 29 },
    9: { temp: 29, condition: "Hot & Humid", waterTemp: 28 },
    10: { temp: 26, condition: "Mild", waterTemp: 26 },
    11: { temp: 22, condition: "Cool", waterTemp: 24 },
    12: { temp: 17, condition: "Cool", waterTemp: 21 },
  },
  // ── TAIWAN ──
  "Taipei": {
    1: { temp: 15, condition: "Cool & Wet", waterTemp: null },
    2: { temp: 16, condition: "Cool & Wet", waterTemp: null },
    3: { temp: 19, condition: "Mild & Wet", waterTemp: null },
    4: { temp: 23, condition: "Mild", waterTemp: null },
    5: { temp: 27, condition: "Warm", waterTemp: null },
    6: { temp: 30, condition: "Hot & Wet", waterTemp: null },
    7: { temp: 33, condition: "Hot", waterTemp: null },
    8: { temp: 33, condition: "Hot", waterTemp: null },
    9: { temp: 29, condition: "Humid", waterTemp: null },
    10: { temp: 25, condition: "Mild", waterTemp: null },
    11: { temp: 20, condition: "Cool", waterTemp: null },
    12: { temp: 16, condition: "Cool", waterTemp: null },
  },
  "Penghu": {
    1: { temp: 15, condition: "Cool & Windy", waterTemp: 22 },
    2: { temp: 15, condition: "Cool & Windy", waterTemp: 21 },
    3: { temp: 18, condition: "Mild", waterTemp: 22 },
    4: { temp: 22, condition: "Mild", waterTemp: 23 },
    5: { temp: 26, condition: "Warm", waterTemp: 25 },
    6: { temp: 29, condition: "Hot", waterTemp: 27 },
    7: { temp: 31, condition: "Hot", waterTemp: 28 },
    8: { temp: 31, condition: "Hot", waterTemp: 29 },
    9: { temp: 28, condition: "Humid", waterTemp: 28 },
    10: { temp: 24, condition: "Mild", waterTemp: 27 },
    11: { temp: 20, condition: "Cool", waterTemp: 25 },
    12: { temp: 16, condition: "Cool & Windy", waterTemp: 23 },
  },
  // ── NEPAL ──
  "Namche Bazaar": {
    1: { temp: -4, condition: "Cold & Dry", waterTemp: null },
    2: { temp: -2, condition: "Cold", waterTemp: null },
    3: { temp: 2, condition: "Cool", waterTemp: null },
    4: { temp: 7, condition: "Mild", waterTemp: null },
    5: { temp: 10, condition: "Mild & Wet", waterTemp: null },
    6: { temp: 13, condition: "Wet", waterTemp: null },
    7: { temp: 14, condition: "Wet", waterTemp: null },
    8: { temp: 14, condition: "Wet", waterTemp: null },
    9: { temp: 11, condition: "Wet", waterTemp: null },
    10: { temp: 5, condition: "Cool & Dry", waterTemp: null },
    11: { temp: -1, condition: "Cold", waterTemp: null },
    12: { temp: -4, condition: "Cold & Dry", waterTemp: null },
  },
  // ── SRI LANKA ──
  "Colombo": {
    1: { temp: 27, condition: "Dry", waterTemp: 28 },
    2: { temp: 28, condition: "Dry", waterTemp: 28 },
    3: { temp: 29, condition: "Hot", waterTemp: 29 },
    4: { temp: 30, condition: "Hot & Wet", waterTemp: 30 },
    5: { temp: 29, condition: "Wet", waterTemp: 30 },
    6: { temp: 28, condition: "Wet", waterTemp: 29 },
    7: { temp: 28, condition: "Wet", waterTemp: 28 },
    8: { temp: 28, condition: "Wet", waterTemp: 28 },
    9: { temp: 28, condition: "Wet", waterTemp: 28 },
    10: { temp: 28, condition: "Wet", waterTemp: 28 },
    11: { temp: 27, condition: "Wet", waterTemp: 28 },
    12: { temp: 27, condition: "Dry", waterTemp: 27 },
  },
  // ── MALDIVES ──
  "Malé": {
    1: { temp: 28, condition: "Dry", waterTemp: 29 },
    2: { temp: 28, condition: "Dry", waterTemp: 29 },
    3: { temp: 29, condition: "Hot & Dry", waterTemp: 29 },
    4: { temp: 29, condition: "Hot", waterTemp: 30 },
    5: { temp: 29, condition: "Wet", waterTemp: 30 },
    6: { temp: 28, condition: "Wet", waterTemp: 29 },
    7: { temp: 28, condition: "Wet", waterTemp: 29 },
    8: { temp: 28, condition: "Wet", waterTemp: 29 },
    9: { temp: 28, condition: "Wet", waterTemp: 29 },
    10: { temp: 28, condition: "Wet", waterTemp: 29 },
    11: { temp: 28, condition: "Dry", waterTemp: 29 },
    12: { temp: 28, condition: "Dry", waterTemp: 29 },
  },
  // ── CAMBODIA ──
  "Siem Reap": {
    1: { temp: 26, condition: "Dry", waterTemp: null },
    2: { temp: 28, condition: "Dry", waterTemp: null },
    3: { temp: 30, condition: "Hot", waterTemp: null },
    4: { temp: 32, condition: "Hot", waterTemp: null },
    5: { temp: 30, condition: "Wet", waterTemp: null },
    6: { temp: 29, condition: "Wet", waterTemp: null },
    7: { temp: 28, condition: "Wet", waterTemp: null },
    8: { temp: 28, condition: "Wet", waterTemp: null },
    9: { temp: 28, condition: "Wet", waterTemp: null },
    10: { temp: 27, condition: "Wet", waterTemp: null },
    11: { temp: 27, condition: "Dry", waterTemp: null },
    12: { temp: 25, condition: "Dry", waterTemp: null },
  },
  // ── MYANMAR ──
  "Bagan": {
    1: { temp: 22, condition: "Dry & Cool", waterTemp: null },
    2: { temp: 25, condition: "Dry", waterTemp: null },
    3: { temp: 30, condition: "Hot", waterTemp: null },
    4: { temp: 34, condition: "Hot", waterTemp: null },
    5: { temp: 33, condition: "Hot", waterTemp: null },
    6: { temp: 30, condition: "Wet", waterTemp: null },
    7: { temp: 29, condition: "Wet", waterTemp: null },
    8: { temp: 29, condition: "Wet", waterTemp: null },
    9: { temp: 29, condition: "Wet", waterTemp: null },
    10: { temp: 28, condition: "Humid", waterTemp: null },
    11: { temp: 25, condition: "Dry", waterTemp: null },
    12: { temp: 21, condition: "Dry & Cool", waterTemp: null },
  },
  // ── MONGOLIA ──
  "Gobi Desert": {
    1: { temp: -15, condition: "Extreme Cold", waterTemp: null },
    2: { temp: -10, condition: "Cold", waterTemp: null },
    3: { temp: -1, condition: "Cold & Windy", waterTemp: null },
    4: { temp: 9, condition: "Cool & Windy", waterTemp: null },
    5: { temp: 18, condition: "Warm", waterTemp: null },
    6: { temp: 24, condition: "Hot & Dry", waterTemp: null },
    7: { temp: 26, condition: "Hot & Dry", waterTemp: null },
    8: { temp: 24, condition: "Hot & Dry", waterTemp: null },
    9: { temp: 15, condition: "Cool", waterTemp: null },
    10: { temp: 5, condition: "Cold", waterTemp: null },
    11: { temp: -6, condition: "Cold", waterTemp: null },
    12: { temp: -13, condition: "Extreme Cold", waterTemp: null },
  },
  // ── BHUTAN ──
  "Thimphu": {
    1: { temp: 5, condition: "Cold & Dry", waterTemp: null },
    2: { temp: 7, condition: "Cold", waterTemp: null },
    3: { temp: 12, condition: "Mild", waterTemp: null },
    4: { temp: 16, condition: "Mild", waterTemp: null },
    5: { temp: 19, condition: "Mild & Wet", waterTemp: null },
    6: { temp: 21, condition: "Wet", waterTemp: null },
    7: { temp: 21, condition: "Wet", waterTemp: null },
    8: { temp: 21, condition: "Wet", waterTemp: null },
    9: { temp: 19, condition: "Wet", waterTemp: null },
    10: { temp: 14, condition: "Cool & Dry", waterTemp: null },
    11: { temp: 9, condition: "Cool", waterTemp: null },
    12: { temp: 5, condition: "Cold", waterTemp: null },
  },
  // ── LAOS ──
  "Luang Prabang": {
    1: { temp: 20, condition: "Dry & Cool", waterTemp: null },
    2: { temp: 23, condition: "Dry", waterTemp: null },
    3: { temp: 27, condition: "Hot", waterTemp: null },
    4: { temp: 30, condition: "Hot", waterTemp: null },
    5: { temp: 28, condition: "Wet", waterTemp: null },
    6: { temp: 27, condition: "Wet", waterTemp: null },
    7: { temp: 27, condition: "Wet", waterTemp: null },
    8: { temp: 27, condition: "Wet", waterTemp: null },
    9: { temp: 26, condition: "Wet", waterTemp: null },
    10: { temp: 25, condition: "Dry", waterTemp: null },
    11: { temp: 22, condition: "Dry", waterTemp: null },
    12: { temp: 19, condition: "Dry & Cool", waterTemp: null },
  },
  // ── UAE ──
  "Dubai": {
    1: { temp: 19, condition: "Mild & Dry", waterTemp: 22 },
    2: { temp: 21, condition: "Mild", waterTemp: 22 },
    3: { temp: 25, condition: "Warm", waterTemp: 24 },
    4: { temp: 30, condition: "Hot", waterTemp: 26 },
    5: { temp: 35, condition: "Hot", waterTemp: 28 },
    6: { temp: 38, condition: "Extreme Heat", waterTemp: 30 },
    7: { temp: 40, condition: "Extreme Heat", waterTemp: 32 },
    8: { temp: 40, condition: "Extreme Heat", waterTemp: 33 },
    9: { temp: 37, condition: "Hot", waterTemp: 32 },
    10: { temp: 32, condition: "Hot", waterTemp: 29 },
    11: { temp: 26, condition: "Warm", waterTemp: 26 },
    12: { temp: 21, condition: "Mild", waterTemp: 23 },
  },
  // ── NEW ZEALAND ──
  "Auckland": {
    1: { temp: 23, condition: "Warm", waterTemp: 21 },
    2: { temp: 23, condition: "Warm", waterTemp: 21 },
    3: { temp: 21, condition: "Mild", waterTemp: 20 },
    4: { temp: 18, condition: "Mild", waterTemp: 18 },
    5: { temp: 15, condition: "Cool", waterTemp: 16 },
    6: { temp: 13, condition: "Cool & Wet", waterTemp: 14 },
    7: { temp: 12, condition: "Cool & Wet", waterTemp: 13 },
    8: { temp: 12, condition: "Cool", waterTemp: 13 },
    9: { temp: 14, condition: "Mild", waterTemp: 14 },
    10: { temp: 16, condition: "Mild", waterTemp: 15 },
    11: { temp: 18, condition: "Mild", waterTemp: 17 },
    12: { temp: 21, condition: "Warm", waterTemp: 19 },
  },
};

// Parse month number from date string like "Jan 12, 2026" or "Nov 30, 2026"
export function parseMonth(dateStr: string): number {
  const months: Record<string, number> = {
    jan: 1, feb: 2, mar: 3, apr: 4, may: 5, jun: 6,
    jul: 7, aug: 8, sep: 9, oct: 10, nov: 11, dec: 12,
  };
  const m = dateStr.toLowerCase().match(/^([a-z]{3})/);
  return m ? (months[m[1]] ?? 0) : 0;
}

// Get weather for a race given its city and date string
export function getRaceWeather(location: string, dateStr: string): WeatherInfo | null {
  const city = location.split(",")[0].trim();
  const month = parseMonth(dateStr);
  if (!month) return null;
  const cityData = CITY_WEATHER[city];
  if (!cityData) return null;
  return cityData[month] ?? null;
}
