// City + month → avg air temp (°C), conditions, water temp (°C where applicable)
// Based on historical climate averages. Month: 1=Jan ... 12=Dec
// waterTemp: relevant for Swim, SwimRun, Triathlon. null = not applicable or unknown.

export interface WeatherInfo {
  temp: number;        // avg air temp °C
  condition: string;   // e.g. "Dry", "Humid", "Wet", "Hot & Humid", "Cool", "Cold"
  waterTemp: number | null; // avg water temp °C (sea/lake), null if unknown/N/A
}

// City-level monthly weather data
// Format: CITY_WEATHER[city][month] = WeatherInfo
export const CITY_WEATHER: Record<string, Record<number, WeatherInfo>> = {
  // ── INDIA ──
  "Chennai": {
    1: { temp: 24, condition: "Dry", waterTemp: 27 },
    2: { temp: 26, condition: "Dry", waterTemp: 27 },
    3: { temp: 29, condition: "Hot", waterTemp: 28 },
    4: { temp: 32, condition: "Hot", waterTemp: 29 },
    5: { temp: 34, condition: "Hot & Humid", waterTemp: 30 },
    6: { temp: 33, condition: "Wet", waterTemp: 30 },
    7: { temp: 31, condition: "Wet", waterTemp: 29 },
    8: { temp: 31, condition: "Wet", waterTemp: 29 },
    9: { temp: 30, condition: "Wet", waterTemp: 29 },
    10: { temp: 28, condition: "Wet", waterTemp: 28 },
    11: { temp: 25, condition: "Humid", waterTemp: 27 },
    12: { temp: 23, condition: "Dry", waterTemp: 27 },
  },
  "Mumbai": {
    1: { temp: 24, condition: "Dry", waterTemp: 25 },
    2: { temp: 25, condition: "Dry", waterTemp: 25 },
    3: { temp: 28, condition: "Hot", waterTemp: 26 },
    4: { temp: 30, condition: "Hot", waterTemp: 27 },
    5: { temp: 32, condition: "Hot & Humid", waterTemp: 28 },
    6: { temp: 30, condition: "Wet", waterTemp: 28 },
    7: { temp: 28, condition: "Wet", waterTemp: 27 },
    8: { temp: 28, condition: "Wet", waterTemp: 27 },
    9: { temp: 28, condition: "Wet", waterTemp: 27 },
    10: { temp: 29, condition: "Humid", waterTemp: 27 },
    11: { temp: 27, condition: "Dry", waterTemp: 26 },
    12: { temp: 24, condition: "Dry", waterTemp: 25 },
  },
  "Goa": {
    1: { temp: 24, condition: "Dry", waterTemp: 27 },
    2: { temp: 25, condition: "Dry", waterTemp: 27 },
    3: { temp: 28, condition: "Hot", waterTemp: 28 },
    4: { temp: 31, condition: "Hot", waterTemp: 29 },
    5: { temp: 32, condition: "Hot & Humid", waterTemp: 30 },
    6: { temp: 29, condition: "Wet", waterTemp: 29 },
    7: { temp: 28, condition: "Wet", waterTemp: 28 },
    8: { temp: 28, condition: "Wet", waterTemp: 28 },
    9: { temp: 28, condition: "Wet", waterTemp: 28 },
    10: { temp: 28, condition: "Humid", waterTemp: 28 },
    11: { temp: 26, condition: "Dry", waterTemp: 27 },
    12: { temp: 24, condition: "Dry", waterTemp: 27 },
  },
  "Bengaluru": {
    1: { temp: 20, condition: "Dry", waterTemp: null },
    2: { temp: 22, condition: "Dry", waterTemp: null },
    3: { temp: 25, condition: "Hot", waterTemp: null },
    4: { temp: 27, condition: "Hot", waterTemp: null },
    5: { temp: 26, condition: "Humid", waterTemp: null },
    6: { temp: 23, condition: "Wet", waterTemp: null },
    7: { temp: 22, condition: "Wet", waterTemp: null },
    8: { temp: 22, condition: "Wet", waterTemp: null },
    9: { temp: 22, condition: "Wet", waterTemp: null },
    10: { temp: 22, condition: "Wet", waterTemp: null },
    11: { temp: 20, condition: "Dry", waterTemp: null },
    12: { temp: 19, condition: "Dry", waterTemp: null },
  },
  "New Delhi": {
    1: { temp: 7, condition: "Cold", waterTemp: null },
    2: { temp: 10, condition: "Cool", waterTemp: null },
    3: { temp: 16, condition: "Dry", waterTemp: null },
    4: { temp: 23, condition: "Hot", waterTemp: null },
    5: { temp: 29, condition: "Hot", waterTemp: null },
    6: { temp: 33, condition: "Hot", waterTemp: null },
    7: { temp: 31, condition: "Wet", waterTemp: null },
    8: { temp: 30, condition: "Wet", waterTemp: null },
    9: { temp: 28, condition: "Wet", waterTemp: null },
    10: { temp: 22, condition: "Dry", waterTemp: null },
    11: { temp: 14, condition: "Cool", waterTemp: null },
    12: { temp: 8, condition: "Cold", waterTemp: null },
  },
  "Kolkata": {
    1: { temp: 18, condition: "Dry", waterTemp: null },
    2: { temp: 21, condition: "Dry", waterTemp: null },
    3: { temp: 26, condition: "Hot", waterTemp: null },
    4: { temp: 30, condition: "Hot", waterTemp: null },
    5: { temp: 32, condition: "Hot & Humid", waterTemp: null },
    6: { temp: 31, condition: "Wet", waterTemp: null },
    7: { temp: 30, condition: "Wet", waterTemp: null },
    8: { temp: 30, condition: "Wet", waterTemp: null },
    9: { temp: 30, condition: "Wet", waterTemp: null },
    10: { temp: 28, condition: "Humid", waterTemp: null },
    11: { temp: 23, condition: "Dry", waterTemp: null },
    12: { temp: 18, condition: "Dry", waterTemp: null },
  },
  "Kevadia": {
    1: { temp: 18, condition: "Dry", waterTemp: null },
    2: { temp: 21, condition: "Dry", waterTemp: null },
    3: { temp: 26, condition: "Hot", waterTemp: null },
    4: { temp: 31, condition: "Hot", waterTemp: null },
    5: { temp: 34, condition: "Hot", waterTemp: null },
    6: { temp: 33, condition: "Wet", waterTemp: null },
    7: { temp: 29, condition: "Wet", waterTemp: null },
    8: { temp: 28, condition: "Wet", waterTemp: null },
    9: { temp: 29, condition: "Wet", waterTemp: null },
    10: { temp: 28, condition: "Dry", waterTemp: null },
    11: { temp: 23, condition: "Dry", waterTemp: null },
    12: { temp: 18, condition: "Dry", waterTemp: null },
  },
  "Ahmedabad": {
    1: { temp: 19, condition: "Dry", waterTemp: null },
    2: { temp: 22, condition: "Dry", waterTemp: null },
    3: { temp: 27, condition: "Hot", waterTemp: null },
    4: { temp: 32, condition: "Hot", waterTemp: null },
    5: { temp: 36, condition: "Hot", waterTemp: null },
    6: { temp: 35, condition: "Wet", waterTemp: null },
    7: { temp: 30, condition: "Wet", waterTemp: null },
    8: { temp: 29, condition: "Wet", waterTemp: null },
    9: { temp: 30, condition: "Wet", waterTemp: null },
    10: { temp: 29, condition: "Dry", waterTemp: null },
    11: { temp: 24, condition: "Dry", waterTemp: null },
    12: { temp: 19, condition: "Dry", waterTemp: null },
  },
  "Hyderabad": {
    1: { temp: 22, condition: "Dry", waterTemp: null },
    2: { temp: 24, condition: "Dry", waterTemp: null },
    3: { temp: 28, condition: "Hot", waterTemp: null },
    4: { temp: 32, condition: "Hot", waterTemp: null },
    5: { temp: 34, condition: "Hot", waterTemp: null },
    6: { temp: 31, condition: "Wet", waterTemp: null },
    7: { temp: 28, condition: "Wet", waterTemp: null },
    8: { temp: 28, condition: "Wet", waterTemp: null },
    9: { temp: 28, condition: "Wet", waterTemp: null },
    10: { temp: 26, condition: "Humid", waterTemp: null },
    11: { temp: 23, condition: "Dry", waterTemp: null },
    12: { temp: 21, condition: "Dry", waterTemp: null },
  },
  "Pune": {
    1: { temp: 19, condition: "Dry", waterTemp: null },
    2: { temp: 21, condition: "Dry", waterTemp: null },
    3: { temp: 25, condition: "Hot", waterTemp: null },
    4: { temp: 29, condition: "Hot", waterTemp: null },
    5: { temp: 31, condition: "Hot", waterTemp: null },
    6: { temp: 28, condition: "Wet", waterTemp: null },
    7: { temp: 25, condition: "Wet", waterTemp: null },
    8: { temp: 25, condition: "Wet", waterTemp: null },
    9: { temp: 25, condition: "Wet", waterTemp: null },
    10: { temp: 25, condition: "Humid", waterTemp: null },
    11: { temp: 22, condition: "Dry", waterTemp: null },
    12: { temp: 19, condition: "Dry", waterTemp: null },
  },
  "Kochi": {
    1: { temp: 26, condition: "Dry", waterTemp: 27 },
    2: { temp: 27, condition: "Dry", waterTemp: 27 },
    3: { temp: 29, condition: "Hot", waterTemp: 28 },
    4: { temp: 30, condition: "Hot & Humid", waterTemp: 29 },
    5: { temp: 29, condition: "Wet", waterTemp: 29 },
    6: { temp: 27, condition: "Wet", waterTemp: 28 },
    7: { temp: 26, condition: "Wet", waterTemp: 27 },
    8: { temp: 26, condition: "Wet", waterTemp: 27 },
    9: { temp: 27, condition: "Wet", waterTemp: 27 },
    10: { temp: 27, condition: "Wet", waterTemp: 27 },
    11: { temp: 27, condition: "Humid", waterTemp: 27 },
    12: { temp: 26, condition: "Dry", waterTemp: 27 },
  },
  "Bikaner": {
    1: { temp: 13, condition: "Dry", waterTemp: null },
    2: { temp: 17, condition: "Dry", waterTemp: null },
    3: { temp: 23, condition: "Hot", waterTemp: null },
    4: { temp: 30, condition: "Hot", waterTemp: null },
    5: { temp: 36, condition: "Hot", waterTemp: null },
    6: { temp: 38, condition: "Hot", waterTemp: null },
    7: { temp: 33, condition: "Wet", waterTemp: null },
    8: { temp: 32, condition: "Wet", waterTemp: null },
    9: { temp: 31, condition: "Wet", waterTemp: null },
    10: { temp: 26, condition: "Dry", waterTemp: null },
    11: { temp: 19, condition: "Dry", waterTemp: null },
    12: { temp: 13, condition: "Dry", waterTemp: null },
  },
  "Auroville": {
    1: { temp: 24, condition: "Dry", waterTemp: 27 },
    2: { temp: 26, condition: "Dry", waterTemp: 27 },
    3: { temp: 29, condition: "Hot", waterTemp: 28 },
    4: { temp: 32, condition: "Hot", waterTemp: 29 },
    5: { temp: 34, condition: "Hot & Humid", waterTemp: 30 },
    6: { temp: 32, condition: "Wet", waterTemp: 30 },
    7: { temp: 31, condition: "Wet", waterTemp: 29 },
    8: { temp: 31, condition: "Wet", waterTemp: 29 },
    9: { temp: 30, condition: "Wet", waterTemp: 29 },
    10: { temp: 28, condition: "Wet", waterTemp: 28 },
    11: { temp: 25, condition: "Humid", waterTemp: 27 },
    12: { temp: 23, condition: "Dry", waterTemp: 27 },
  },
  "Kaveri": {
    1: { temp: 22, condition: "Dry", waterTemp: null },
    2: { temp: 24, condition: "Dry", waterTemp: null },
    3: { temp: 28, condition: "Hot", waterTemp: null },
    4: { temp: 31, condition: "Hot", waterTemp: null },
    5: { temp: 32, condition: "Hot", waterTemp: null },
    6: { temp: 28, condition: "Wet", waterTemp: null },
    7: { temp: 27, condition: "Wet", waterTemp: null },
    8: { temp: 27, condition: "Wet", waterTemp: null },
    9: { temp: 27, condition: "Wet", waterTemp: null },
    10: { temp: 26, condition: "Wet", waterTemp: null },
    11: { temp: 23, condition: "Dry", waterTemp: null },
    12: { temp: 21, condition: "Dry", waterTemp: null },
  },
  // ── JAPAN ──
  "Tokyo": {
    1: { temp: 5, condition: "Cold & Dry", waterTemp: 16 },
    2: { temp: 6, condition: "Cold & Dry", waterTemp: 15 },
    3: { temp: 10, condition: "Cool", waterTemp: 16 },
    4: { temp: 15, condition: "Mild", waterTemp: 17 },
    5: { temp: 20, condition: "Mild", waterTemp: 19 },
    6: { temp: 23, condition: "Humid", waterTemp: 21 },
    7: { temp: 27, condition: "Hot & Humid", waterTemp: 24 },
    8: { temp: 29, condition: "Hot & Humid", waterTemp: 26 },
    9: { temp: 25, condition: "Humid", waterTemp: 25 },
    10: { temp: 18, condition: "Mild", waterTemp: 23 },
    11: { temp: 12, condition: "Cool", waterTemp: 20 },
    12: { temp: 7, condition: "Cold", waterTemp: 18 },
  },
  "Osaka": {
    1: { temp: 5, condition: "Cold", waterTemp: null },
    2: { temp: 6, condition: "Cold", waterTemp: null },
    3: { temp: 10, condition: "Cool", waterTemp: null },
    4: { temp: 16, condition: "Mild", waterTemp: null },
    5: { temp: 21, condition: "Mild", waterTemp: null },
    6: { temp: 25, condition: "Humid", waterTemp: null },
    7: { temp: 29, condition: "Hot & Humid", waterTemp: null },
    8: { temp: 31, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 26, condition: "Humid", waterTemp: null },
    10: { temp: 19, condition: "Mild", waterTemp: null },
    11: { temp: 13, condition: "Cool", waterTemp: null },
    12: { temp: 7, condition: "Cold", waterTemp: null },
  },
  "Kyoto": {
    1: { temp: 4, condition: "Cold", waterTemp: null },
    2: { temp: 5, condition: "Cold", waterTemp: null },
    3: { temp: 9, condition: "Cool", waterTemp: null },
    4: { temp: 16, condition: "Mild", waterTemp: null },
    5: { temp: 21, condition: "Mild", waterTemp: null },
    6: { temp: 25, condition: "Humid", waterTemp: null },
    7: { temp: 29, condition: "Hot & Humid", waterTemp: null },
    8: { temp: 31, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 26, condition: "Humid", waterTemp: null },
    10: { temp: 19, condition: "Mild", waterTemp: null },
    11: { temp: 12, condition: "Cool", waterTemp: null },
    12: { temp: 6, condition: "Cold", waterTemp: null },
  },
  "Nagoya": {
    1: { temp: 4, condition: "Cold", waterTemp: null },
    2: { temp: 5, condition: "Cold", waterTemp: null },
    3: { temp: 9, condition: "Cool", waterTemp: null },
    4: { temp: 16, condition: "Mild", waterTemp: null },
    5: { temp: 21, condition: "Mild", waterTemp: null },
    6: { temp: 25, condition: "Humid", waterTemp: null },
    7: { temp: 29, condition: "Hot & Humid", waterTemp: null },
    8: { temp: 31, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 26, condition: "Humid", waterTemp: null },
    10: { temp: 19, condition: "Mild", waterTemp: null },
    11: { temp: 12, condition: "Cool", waterTemp: null },
    12: { temp: 6, condition: "Cold", waterTemp: null },
  },
  "Yokohama": {
    1: { temp: 5, condition: "Cold", waterTemp: 16 },
    2: { temp: 6, condition: "Cold", waterTemp: 15 },
    3: { temp: 10, condition: "Cool", waterTemp: 16 },
    4: { temp: 15, condition: "Mild", waterTemp: 17 },
    5: { temp: 20, condition: "Mild", waterTemp: 19 },
    6: { temp: 23, condition: "Humid", waterTemp: 21 },
    7: { temp: 27, condition: "Hot & Humid", waterTemp: 24 },
    8: { temp: 29, condition: "Hot & Humid", waterTemp: 26 },
    9: { temp: 25, condition: "Humid", waterTemp: 25 },
    10: { temp: 18, condition: "Mild", waterTemp: 23 },
    11: { temp: 12, condition: "Cool", waterTemp: 20 },
    12: { temp: 7, condition: "Cold", waterTemp: 18 },
  },
  "Sapporo": {
    1: { temp: -4, condition: "Cold & Snowy", waterTemp: 3 },
    2: { temp: -3, condition: "Cold & Snowy", waterTemp: 2 },
    3: { temp: 2, condition: "Cold", waterTemp: 3 },
    4: { temp: 9, condition: "Cool", waterTemp: 6 },
    5: { temp: 15, condition: "Mild", waterTemp: 10 },
    6: { temp: 19, condition: "Mild", waterTemp: 13 },
    7: { temp: 23, condition: "Humid", waterTemp: 17 },
    8: { temp: 24, condition: "Hot & Humid", waterTemp: 20 },
    9: { temp: 19, condition: "Mild", waterTemp: 18 },
    10: { temp: 12, condition: "Cool", waterTemp: 15 },
    11: { temp: 4, condition: "Cool", waterTemp: 9 },
    12: { temp: -2, condition: "Cold & Snowy", waterTemp: 5 },
  },
  "Fukuoka": {
    1: { temp: 7, condition: "Cold", waterTemp: 14 },
    2: { temp: 8, condition: "Cold", waterTemp: 13 },
    3: { temp: 12, condition: "Cool", waterTemp: 15 },
    4: { temp: 17, condition: "Mild", waterTemp: 17 },
    5: { temp: 22, condition: "Mild", waterTemp: 20 },
    6: { temp: 25, condition: "Humid", waterTemp: 23 },
    7: { temp: 29, condition: "Hot & Humid", waterTemp: 26 },
    8: { temp: 30, condition: "Hot & Humid", waterTemp: 28 },
    9: { temp: 26, condition: "Humid", waterTemp: 26 },
    10: { temp: 20, condition: "Mild", waterTemp: 23 },
    11: { temp: 14, condition: "Cool", waterTemp: 19 },
    12: { temp: 9, condition: "Cold", waterTemp: 16 },
  },
  "Beppu": {
    1: { temp: 7, condition: "Cold", waterTemp: 15 },
    2: { temp: 8, condition: "Cold", waterTemp: 14 },
    3: { temp: 12, condition: "Cool", waterTemp: 15 },
    4: { temp: 17, condition: "Mild", waterTemp: 17 },
    5: { temp: 22, condition: "Mild", waterTemp: 20 },
    6: { temp: 25, condition: "Humid", waterTemp: 23 },
    7: { temp: 29, condition: "Hot & Humid", waterTemp: 26 },
    8: { temp: 30, condition: "Hot & Humid", waterTemp: 28 },
    9: { temp: 26, condition: "Humid", waterTemp: 26 },
    10: { temp: 20, condition: "Mild", waterTemp: 23 },
    11: { temp: 14, condition: "Cool", waterTemp: 19 },
    12: { temp: 9, condition: "Cold", waterTemp: 16 },
  },
  "Miyazaki": {
    1: { temp: 9, condition: "Cool", waterTemp: 17 },
    2: { temp: 10, condition: "Cool", waterTemp: 16 },
    3: { temp: 13, condition: "Mild", waterTemp: 17 },
    4: { temp: 18, condition: "Mild", waterTemp: 19 },
    5: { temp: 22, condition: "Mild", waterTemp: 21 },
    6: { temp: 25, condition: "Humid", waterTemp: 23 },
    7: { temp: 28, condition: "Hot & Humid", waterTemp: 26 },
    8: { temp: 29, condition: "Hot & Humid", waterTemp: 28 },
    9: { temp: 26, condition: "Humid", waterTemp: 27 },
    10: { temp: 21, condition: "Mild", waterTemp: 24 },
    11: { temp: 15, condition: "Cool", waterTemp: 21 },
    12: { temp: 10, condition: "Cool", waterTemp: 18 },
  },
  "Naha": {
    1: { temp: 17, condition: "Cool", waterTemp: 22 },
    2: { temp: 17, condition: "Cool", waterTemp: 21 },
    3: { temp: 19, condition: "Mild", waterTemp: 22 },
    4: { temp: 22, condition: "Mild", waterTemp: 24 },
    5: { temp: 25, condition: "Humid", waterTemp: 26 },
    6: { temp: 28, condition: "Wet", waterTemp: 28 },
    7: { temp: 30, condition: "Hot & Humid", waterTemp: 29 },
    8: { temp: 30, condition: "Hot & Humid", waterTemp: 30 },
    9: { temp: 28, condition: "Humid", waterTemp: 29 },
    10: { temp: 25, condition: "Mild", waterTemp: 27 },
    11: { temp: 22, condition: "Mild", waterTemp: 25 },
    12: { temp: 18, condition: "Cool", waterTemp: 23 },
  },
  "Okinawa": {
    1: { temp: 17, condition: "Cool", waterTemp: 22 },
    2: { temp: 17, condition: "Cool", waterTemp: 21 },
    3: { temp: 19, condition: "Mild", waterTemp: 22 },
    4: { temp: 22, condition: "Mild", waterTemp: 24 },
    5: { temp: 25, condition: "Humid", waterTemp: 26 },
    6: { temp: 28, condition: "Wet", waterTemp: 28 },
    7: { temp: 30, condition: "Hot & Humid", waterTemp: 29 },
    8: { temp: 30, condition: "Hot & Humid", waterTemp: 30 },
    9: { temp: 28, condition: "Humid", waterTemp: 29 },
    10: { temp: 25, condition: "Mild", waterTemp: 27 },
    11: { temp: 22, condition: "Mild", waterTemp: 25 },
    12: { temp: 18, condition: "Cool", waterTemp: 23 },
  },
  "Ishigaki": {
    1: { temp: 18, condition: "Cool", waterTemp: 23 },
    2: { temp: 18, condition: "Cool", waterTemp: 22 },
    3: { temp: 20, condition: "Mild", waterTemp: 23 },
    4: { temp: 23, condition: "Mild", waterTemp: 25 },
    5: { temp: 26, condition: "Humid", waterTemp: 27 },
    6: { temp: 28, condition: "Wet", waterTemp: 29 },
    7: { temp: 30, condition: "Hot & Humid", waterTemp: 30 },
    8: { temp: 30, condition: "Hot & Humid", waterTemp: 31 },
    9: { temp: 29, condition: "Humid", waterTemp: 30 },
    10: { temp: 26, condition: "Mild", waterTemp: 28 },
    11: { temp: 23, condition: "Mild", waterTemp: 26 },
    12: { temp: 19, condition: "Cool", waterTemp: 24 },
  },
  "Nagano": {
    1: { temp: -2, condition: "Cold & Snowy", waterTemp: null },
    2: { temp: -1, condition: "Cold & Snowy", waterTemp: null },
    3: { temp: 4, condition: "Cold", waterTemp: null },
    4: { temp: 11, condition: "Cool", waterTemp: null },
    5: { temp: 17, condition: "Mild", waterTemp: null },
    6: { temp: 21, condition: "Mild", waterTemp: null },
    7: { temp: 25, condition: "Hot & Humid", waterTemp: null },
    8: { temp: 26, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 21, condition: "Humid", waterTemp: null },
    10: { temp: 14, condition: "Cool", waterTemp: null },
    11: { temp: 7, condition: "Cool", waterTemp: null },
    12: { temp: 1, condition: "Cold", waterTemp: null },
  },
  "Nara": {
    1: { temp: 4, condition: "Cold", waterTemp: null },
    2: { temp: 5, condition: "Cold", waterTemp: null },
    3: { temp: 9, condition: "Cool", waterTemp: null },
    4: { temp: 15, condition: "Mild", waterTemp: null },
    5: { temp: 21, condition: "Mild", waterTemp: null },
    6: { temp: 24, condition: "Humid", waterTemp: null },
    7: { temp: 29, condition: "Hot & Humid", waterTemp: null },
    8: { temp: 31, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 26, condition: "Humid", waterTemp: null },
    10: { temp: 19, condition: "Mild", waterTemp: null },
    11: { temp: 12, condition: "Cool", waterTemp: null },
    12: { temp: 6, condition: "Cold", waterTemp: null },
  },
  "Kanazawa": {
    1: { temp: 3, condition: "Cold & Wet", waterTemp: null },
    2: { temp: 4, condition: "Cold & Wet", waterTemp: null },
    3: { temp: 8, condition: "Cool", waterTemp: null },
    4: { temp: 14, condition: "Mild", waterTemp: null },
    5: { temp: 19, condition: "Mild", waterTemp: null },
    6: { temp: 23, condition: "Humid", waterTemp: null },
    7: { temp: 28, condition: "Hot & Humid", waterTemp: null },
    8: { temp: 30, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 25, condition: "Humid", waterTemp: null },
    10: { temp: 18, condition: "Mild", waterTemp: null },
    11: { temp: 12, condition: "Cool", waterTemp: null },
    12: { temp: 5, condition: "Cold", waterTemp: null },
  },
  "Noto, Ishikawa": {
    1: { temp: 3, condition: "Cold & Wet", waterTemp: null },
    2: { temp: 4, condition: "Cold & Wet", waterTemp: null },
    3: { temp: 8, condition: "Cool", waterTemp: null },
    4: { temp: 14, condition: "Mild", waterTemp: null },
    5: { temp: 19, condition: "Mild", waterTemp: null },
    6: { temp: 23, condition: "Humid", waterTemp: null },
    7: { temp: 28, condition: "Hot & Humid", waterTemp: null },
    8: { temp: 30, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 25, condition: "Humid", waterTemp: null },
    10: { temp: 18, condition: "Mild", waterTemp: null },
    11: { temp: 12, condition: "Cool", waterTemp: null },
    12: { temp: 5, condition: "Cold", waterTemp: null },
  },
  "Niigata": {
    1: { temp: 2, condition: "Cold & Wet", waterTemp: null },
    2: { temp: 3, condition: "Cold", waterTemp: null },
    3: { temp: 7, condition: "Cool", waterTemp: null },
    4: { temp: 13, condition: "Mild", waterTemp: null },
    5: { temp: 18, condition: "Mild", waterTemp: null },
    6: { temp: 22, condition: "Humid", waterTemp: null },
    7: { temp: 27, condition: "Hot & Humid", waterTemp: null },
    8: { temp: 29, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 24, condition: "Humid", waterTemp: null },
    10: { temp: 17, condition: "Mild", waterTemp: null },
    11: { temp: 11, condition: "Cool", waterTemp: null },
    12: { temp: 4, condition: "Cold", waterTemp: null },
  },
  "Myoko City Niigata": {
    1: { temp: 2, condition: "Cold & Wet", waterTemp: null },
    2: { temp: 3, condition: "Cold", waterTemp: null },
    3: { temp: 7, condition: "Cool", waterTemp: null },
    4: { temp: 13, condition: "Mild", waterTemp: null },
    5: { temp: 18, condition: "Mild", waterTemp: null },
    6: { temp: 22, condition: "Humid", waterTemp: null },
    7: { temp: 27, condition: "Hot & Humid", waterTemp: null },
    8: { temp: 29, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 24, condition: "Humid", waterTemp: null },
    10: { temp: 17, condition: "Mild", waterTemp: null },
    11: { temp: 11, condition: "Cool", waterTemp: null },
    12: { temp: 4, condition: "Cold", waterTemp: null },
  },
  // ── THAILAND ──
  "Bangkok": {
    1: { temp: 27, condition: "Dry", waterTemp: null },
    2: { temp: 29, condition: "Dry", waterTemp: null },
    3: { temp: 31, condition: "Hot", waterTemp: null },
    4: { temp: 33, condition: "Hot", waterTemp: null },
    5: { temp: 31, condition: "Wet", waterTemp: null },
    6: { temp: 30, condition: "Wet", waterTemp: null },
    7: { temp: 29, condition: "Wet", waterTemp: null },
    8: { temp: 29, condition: "Wet", waterTemp: null },
    9: { temp: 29, condition: "Wet", waterTemp: null },
    10: { temp: 28, condition: "Wet", waterTemp: null },
    11: { temp: 27, condition: "Dry", waterTemp: null },
    12: { temp: 26, condition: "Dry", waterTemp: null },
  },
  "Phuket": {
    1: { temp: 27, condition: "Dry", waterTemp: 28 },
    2: { temp: 28, condition: "Dry", waterTemp: 28 },
    3: { temp: 29, condition: "Dry", waterTemp: 29 },
    4: { temp: 30, condition: "Hot", waterTemp: 30 },
    5: { temp: 29, condition: "Wet", waterTemp: 29 },
    6: { temp: 28, condition: "Wet", waterTemp: 29 },
    7: { temp: 28, condition: "Wet", waterTemp: 28 },
    8: { temp: 28, condition: "Wet", waterTemp: 28 },
    9: { temp: 27, condition: "Wet", waterTemp: 28 },
    10: { temp: 27, condition: "Wet", waterTemp: 28 },
    11: { temp: 27, condition: "Dry", waterTemp: 28 },
    12: { temp: 27, condition: "Dry", waterTemp: 28 },
  },
  "Thalang, Phuket": {
    1: { temp: 27, condition: "Dry", waterTemp: 28 },
    2: { temp: 28, condition: "Dry", waterTemp: 28 },
    3: { temp: 29, condition: "Dry", waterTemp: 29 },
    4: { temp: 30, condition: "Hot", waterTemp: 30 },
    5: { temp: 29, condition: "Wet", waterTemp: 29 },
    6: { temp: 28, condition: "Wet", waterTemp: 29 },
    7: { temp: 28, condition: "Wet", waterTemp: 28 },
    8: { temp: 28, condition: "Wet", waterTemp: 28 },
    9: { temp: 27, condition: "Wet", waterTemp: 28 },
    10: { temp: 27, condition: "Wet", waterTemp: 28 },
    11: { temp: 27, condition: "Dry", waterTemp: 28 },
    12: { temp: 27, condition: "Dry", waterTemp: 28 },
  },
  "Chiang Mai": {
    1: { temp: 18, condition: "Dry & Cool", waterTemp: null },
    2: { temp: 21, condition: "Dry", waterTemp: null },
    3: { temp: 26, condition: "Hot", waterTemp: null },
    4: { temp: 30, condition: "Hot", waterTemp: null },
    5: { temp: 28, condition: "Wet", waterTemp: null },
    6: { temp: 27, condition: "Wet", waterTemp: null },
    7: { temp: 27, condition: "Wet", waterTemp: null },
    8: { temp: 27, condition: "Wet", waterTemp: null },
    9: { temp: 26, condition: "Wet", waterTemp: null },
    10: { temp: 25, condition: "Humid", waterTemp: null },
    11: { temp: 22, condition: "Dry", waterTemp: null },
    12: { temp: 18, condition: "Dry & Cool", waterTemp: null },
  },
  "Chiang Rai": {
    1: { temp: 16, condition: "Cool", waterTemp: null },
    2: { temp: 19, condition: "Dry", waterTemp: null },
    3: { temp: 24, condition: "Hot", waterTemp: null },
    4: { temp: 28, condition: "Hot", waterTemp: null },
    5: { temp: 26, condition: "Wet", waterTemp: null },
    6: { temp: 25, condition: "Wet", waterTemp: null },
    7: { temp: 25, condition: "Wet", waterTemp: null },
    8: { temp: 25, condition: "Wet", waterTemp: null },
    9: { temp: 24, condition: "Wet", waterTemp: null },
    10: { temp: 23, condition: "Humid", waterTemp: null },
    11: { temp: 20, condition: "Dry", waterTemp: null },
    12: { temp: 16, condition: "Cool", waterTemp: null },
  },
  "Krabi": {
    1: { temp: 27, condition: "Dry", waterTemp: 28 },
    2: { temp: 28, condition: "Dry", waterTemp: 28 },
    3: { temp: 29, condition: "Dry", waterTemp: 29 },
    4: { temp: 30, condition: "Hot", waterTemp: 30 },
    5: { temp: 29, condition: "Wet", waterTemp: 30 },
    6: { temp: 28, condition: "Wet", waterTemp: 29 },
    7: { temp: 28, condition: "Wet", waterTemp: 28 },
    8: { temp: 28, condition: "Wet", waterTemp: 28 },
    9: { temp: 27, condition: "Wet", waterTemp: 28 },
    10: { temp: 27, condition: "Wet", waterTemp: 28 },
    11: { temp: 27, condition: "Humid", waterTemp: 28 },
    12: { temp: 27, condition: "Dry", waterTemp: 28 },
  },
  "Ao Nang": {
    1: { temp: 27, condition: "Dry", waterTemp: 28 },
    2: { temp: 28, condition: "Dry", waterTemp: 28 },
    3: { temp: 29, condition: "Dry", waterTemp: 29 },
    4: { temp: 30, condition: "Hot", waterTemp: 30 },
    5: { temp: 29, condition: "Wet", waterTemp: 30 },
    6: { temp: 28, condition: "Wet", waterTemp: 29 },
    7: { temp: 28, condition: "Wet", waterTemp: 28 },
    8: { temp: 28, condition: "Wet", waterTemp: 28 },
    9: { temp: 27, condition: "Wet", waterTemp: 28 },
    10: { temp: 27, condition: "Wet", waterTemp: 28 },
    11: { temp: 27, condition: "Humid", waterTemp: 28 },
    12: { temp: 27, condition: "Dry", waterTemp: 28 },
  },
  "Koh Samui": {
    1: { temp: 26, condition: "Dry", waterTemp: 27 },
    2: { temp: 27, condition: "Dry", waterTemp: 27 },
    3: { temp: 28, condition: "Dry", waterTemp: 28 },
    4: { temp: 29, condition: "Hot", waterTemp: 29 },
    5: { temp: 29, condition: "Wet", waterTemp: 29 },
    6: { temp: 29, condition: "Wet", waterTemp: 29 },
    7: { temp: 28, condition: "Wet", waterTemp: 29 },
    8: { temp: 28, condition: "Wet", waterTemp: 29 },
    9: { temp: 27, condition: "Wet", waterTemp: 28 },
    10: { temp: 26, condition: "Wet", waterTemp: 27 },
    11: { temp: 25, condition: "Wet", waterTemp: 27 },
    12: { temp: 25, condition: "Humid", waterTemp: 27 },
  },
  "Buriram": {
    1: { temp: 24, condition: "Dry", waterTemp: null },
    2: { temp: 27, condition: "Dry", waterTemp: null },
    3: { temp: 30, condition: "Hot", waterTemp: null },
    4: { temp: 32, condition: "Hot", waterTemp: null },
    5: { temp: 30, condition: "Wet", waterTemp: null },
    6: { temp: 29, condition: "Wet", waterTemp: null },
    7: { temp: 28, condition: "Wet", waterTemp: null },
    8: { temp: 28, condition: "Wet", waterTemp: null },
    9: { temp: 28, condition: "Wet", waterTemp: null },
    10: { temp: 27, condition: "Wet", waterTemp: null },
    11: { temp: 26, condition: "Dry", waterTemp: null },
    12: { temp: 23, condition: "Dry", waterTemp: null },
  },
  // ── VIETNAM ──
  "Ho Chi Minh City": {
    1: { temp: 27, condition: "Dry", waterTemp: null },
    2: { temp: 28, condition: "Dry", waterTemp: null },
    3: { temp: 30, condition: "Hot", waterTemp: null },
    4: { temp: 31, condition: "Hot", waterTemp: null },
    5: { temp: 29, condition: "Wet", waterTemp: null },
    6: { temp: 28, condition: "Wet", waterTemp: null },
    7: { temp: 27, condition: "Wet", waterTemp: null },
    8: { temp: 27, condition: "Wet", waterTemp: null },
    9: { temp: 27, condition: "Wet", waterTemp: null },
    10: { temp: 27, condition: "Wet", waterTemp: null },
    11: { temp: 27, condition: "Humid", waterTemp: null },
    12: { temp: 26, condition: "Dry", waterTemp: null },
  },
  "Hanoi": {
    1: { temp: 17, condition: "Cool & Drizzly", waterTemp: null },
    2: { temp: 18, condition: "Cool & Drizzly", waterTemp: null },
    3: { temp: 21, condition: "Humid", waterTemp: null },
    4: { temp: 25, condition: "Humid", waterTemp: null },
    5: { temp: 29, condition: "Hot & Humid", waterTemp: null },
    6: { temp: 31, condition: "Hot & Wet", waterTemp: null },
    7: { temp: 31, condition: "Hot & Wet", waterTemp: null },
    8: { temp: 30, condition: "Hot & Wet", waterTemp: null },
    9: { temp: 29, condition: "Wet", waterTemp: null },
    10: { temp: 26, condition: "Dry", waterTemp: null },
    11: { temp: 22, condition: "Cool", waterTemp: null },
    12: { temp: 18, condition: "Cool", waterTemp: null },
  },
  "Sapa": {
    1: { temp: 10, condition: "Cold & Misty", waterTemp: null },
    2: { temp: 11, condition: "Cold & Misty", waterTemp: null },
    3: { temp: 14, condition: "Cool & Misty", waterTemp: null },
    4: { temp: 18, condition: "Mild", waterTemp: null },
    5: { temp: 20, condition: "Mild & Wet", waterTemp: null },
    6: { temp: 21, condition: "Wet", waterTemp: null },
    7: { temp: 21, condition: "Wet", waterTemp: null },
    8: { temp: 21, condition: "Wet", waterTemp: null },
    9: { temp: 19, condition: "Wet", waterTemp: null },
    10: { temp: 16, condition: "Cool", waterTemp: null },
    11: { temp: 12, condition: "Cool", waterTemp: null },
    12: { temp: 9, condition: "Cold", waterTemp: null },
  },
  "Da Nang": {
    1: { temp: 21, condition: "Cool & Wet", waterTemp: 24 },
    2: { temp: 22, condition: "Cool", waterTemp: 24 },
    3: { temp: 24, condition: "Mild", waterTemp: 25 },
    4: { temp: 27, condition: "Dry", waterTemp: 26 },
    5: { temp: 30, condition: "Hot", waterTemp: 27 },
    6: { temp: 31, condition: "Hot", waterTemp: 28 },
    7: { temp: 31, condition: "Hot", waterTemp: 28 },
    8: { temp: 31, condition: "Hot & Wet", waterTemp: 29 },
    9: { temp: 29, condition: "Wet", waterTemp: 28 },
    10: { temp: 26, condition: "Wet", waterTemp: 27 },
    11: { temp: 23, condition: "Wet", waterTemp: 25 },
    12: { temp: 21, condition: "Cool & Wet", waterTemp: 24 },
  },
  "Nha Trang": {
    1: { temp: 24, condition: "Dry", waterTemp: 25 },
    2: { temp: 25, condition: "Dry", waterTemp: 25 },
    3: { temp: 27, condition: "Dry", waterTemp: 26 },
    4: { temp: 29, condition: "Hot", waterTemp: 27 },
    5: { temp: 30, condition: "Hot", waterTemp: 28 },
    6: { temp: 29, condition: "Wet", waterTemp: 29 },
    7: { temp: 29, condition: "Wet", waterTemp: 29 },
    8: { temp: 29, condition: "Wet", waterTemp: 29 },
    9: { temp: 28, condition: "Wet", waterTemp: 28 },
    10: { temp: 27, condition: "Wet", waterTemp: 27 },
    11: { temp: 25, condition: "Wet", waterTemp: 26 },
    12: { temp: 24, condition: "Humid", waterTemp: 25 },
  },
  "Can Tho": {
    1: { temp: 27, condition: "Dry", waterTemp: null },
    2: { temp: 28, condition: "Dry", waterTemp: null },
    3: { temp: 30, condition: "Hot", waterTemp: null },
    4: { temp: 31, condition: "Hot", waterTemp: null },
    5: { temp: 30, condition: "Wet", waterTemp: null },
    6: { temp: 29, condition: "Wet", waterTemp: null },
    7: { temp: 28, condition: "Wet", waterTemp: null },
    8: { temp: 28, condition: "Wet", waterTemp: null },
    9: { temp: 28, condition: "Wet", waterTemp: null },
    10: { temp: 27, condition: "Wet", waterTemp: null },
    11: { temp: 27, condition: "Humid", waterTemp: null },
    12: { temp: 26, condition: "Dry", waterTemp: null },
  },
  // ── PHILIPPINES ──
  "Manila": {
    1: { temp: 26, condition: "Dry", waterTemp: 27 },
    2: { temp: 27, condition: "Dry", waterTemp: 27 },
    3: { temp: 29, condition: "Hot", waterTemp: 28 },
    4: { temp: 31, condition: "Hot", waterTemp: 29 },
    5: { temp: 31, condition: "Hot & Wet", waterTemp: 30 },
    6: { temp: 29, condition: "Wet", waterTemp: 30 },
    7: { temp: 28, condition: "Wet", waterTemp: 29 },
    8: { temp: 28, condition: "Wet", waterTemp: 29 },
    9: { temp: 28, condition: "Wet", waterTemp: 29 },
    10: { temp: 28, condition: "Wet", waterTemp: 29 },
    11: { temp: 27, condition: "Humid", waterTemp: 28 },
    12: { temp: 26, condition: "Dry", waterTemp: 27 },
  },
  "Subic Bay": {
    1: { temp: 25, condition: "Dry", waterTemp: 27 },
    2: { temp: 26, condition: "Dry", waterTemp: 27 },
    3: { temp: 28, condition: "Hot", waterTemp: 28 },
    4: { temp: 30, condition: "Hot", waterTemp: 29 },
    5: { temp: 30, condition: "Hot & Wet", waterTemp: 30 },
    6: { temp: 28, condition: "Wet", waterTemp: 29 },
    7: { temp: 27, condition: "Wet", waterTemp: 29 },
    8: { temp: 27, condition: "Wet", waterTemp: 29 },
    9: { temp: 27, condition: "Wet", waterTemp: 29 },
    10: { temp: 27, condition: "Wet", waterTemp: 28 },
    11: { temp: 26, condition: "Humid", waterTemp: 27 },
    12: { temp: 25, condition: "Dry", waterTemp: 27 },
  },
  "Mactan": {
    1: { temp: 27, condition: "Dry", waterTemp: 27 },
    2: { temp: 28, condition: "Dry", waterTemp: 27 },
    3: { temp: 29, condition: "Hot", waterTemp: 28 },
    4: { temp: 31, condition: "Hot", waterTemp: 29 },
    5: { temp: 31, condition: "Hot & Wet", waterTemp: 30 },
    6: { temp: 29, condition: "Wet", waterTemp: 29 },
    7: { temp: 28, condition: "Wet", waterTemp: 29 },
    8: { temp: 28, condition: "Wet", waterTemp: 29 },
    9: { temp: 28, condition: "Wet", waterTemp: 29 },
    10: { temp: 28, condition: "Wet", waterTemp: 28 },
    11: { temp: 27, condition: "Humid", waterTemp: 28 },
    12: { temp: 27, condition: "Dry", waterTemp: 27 },
  },
  "Cebu": {
    1: { temp: 27, condition: "Dry", waterTemp: 27 },
    2: { temp: 28, condition: "Dry", waterTemp: 27 },
    3: { temp: 29, condition: "Hot", waterTemp: 28 },
    4: { temp: 31, condition: "Hot", waterTemp: 29 },
    5: { temp: 31, condition: "Hot & Wet", waterTemp: 30 },
    6: { temp: 29, condition: "Wet", waterTemp: 29 },
    7: { temp: 28, condition: "Wet", waterTemp: 29 },
    8: { temp: 28, condition: "Wet", waterTemp: 29 },
    9: { temp: 28, condition: "Wet", waterTemp: 29 },
    10: { temp: 28, condition: "Wet", waterTemp: 28 },
    11: { temp: 27, condition: "Humid", waterTemp: 28 },
    12: { temp: 27, condition: "Dry", waterTemp: 27 },
  },
  "Luzon": {
    1: { temp: 25, condition: "Dry", waterTemp: 27 },
    2: { temp: 26, condition: "Dry", waterTemp: 27 },
    3: { temp: 28, condition: "Hot", waterTemp: 28 },
    4: { temp: 30, condition: "Hot", waterTemp: 29 },
    5: { temp: 30, condition: "Hot & Wet", waterTemp: 30 },
    6: { temp: 28, condition: "Wet", waterTemp: 29 },
    7: { temp: 27, condition: "Wet", waterTemp: 29 },
    8: { temp: 27, condition: "Wet", waterTemp: 29 },
    9: { temp: 27, condition: "Wet", waterTemp: 29 },
    10: { temp: 27, condition: "Wet", waterTemp: 28 },
    11: { temp: 26, condition: "Humid", waterTemp: 27 },
    12: { temp: 25, condition: "Dry", waterTemp: 27 },
  },
  // ── INDONESIA ──
  "Bali": {
    1: { temp: 27, condition: "Wet", waterTemp: 28 },
    2: { temp: 27, condition: "Wet", waterTemp: 28 },
    3: { temp: 28, condition: "Wet", waterTemp: 28 },
    4: { temp: 28, condition: "Humid", waterTemp: 29 },
    5: { temp: 27, condition: "Dry", waterTemp: 28 },
    6: { temp: 26, condition: "Dry & Cool", waterTemp: 27 },
    7: { temp: 25, condition: "Dry & Cool", waterTemp: 26 },
    8: { temp: 25, condition: "Dry & Cool", waterTemp: 26 },
    9: { temp: 26, condition: "Dry", waterTemp: 27 },
    10: { temp: 27, condition: "Dry", waterTemp: 28 },
    11: { temp: 27, condition: "Wet", waterTemp: 28 },
    12: { temp: 27, condition: "Wet", waterTemp: 28 },
  },
  "Lombok": {
    1: { temp: 27, condition: "Wet", waterTemp: 28 },
    2: { temp: 27, condition: "Wet", waterTemp: 28 },
    3: { temp: 27, condition: "Wet", waterTemp: 28 },
    4: { temp: 28, condition: "Humid", waterTemp: 29 },
    5: { temp: 27, condition: "Dry", waterTemp: 28 },
    6: { temp: 25, condition: "Dry & Cool", waterTemp: 27 },
    7: { temp: 24, condition: "Dry & Cool", waterTemp: 26 },
    8: { temp: 24, condition: "Dry & Cool", waterTemp: 26 },
    9: { temp: 25, condition: "Dry", waterTemp: 27 },
    10: { temp: 27, condition: "Dry", waterTemp: 28 },
    11: { temp: 27, condition: "Wet", waterTemp: 28 },
    12: { temp: 27, condition: "Wet", waterTemp: 28 },
  },
  "Jakarta": {
    1: { temp: 27, condition: "Wet", waterTemp: null },
    2: { temp: 27, condition: "Wet", waterTemp: null },
    3: { temp: 28, condition: "Wet", waterTemp: null },
    4: { temp: 29, condition: "Humid", waterTemp: null },
    5: { temp: 29, condition: "Dry", waterTemp: null },
    6: { temp: 28, condition: "Dry", waterTemp: null },
    7: { temp: 28, condition: "Dry", waterTemp: null },
    8: { temp: 28, condition: "Dry", waterTemp: null },
    9: { temp: 29, condition: "Dry", waterTemp: null },
    10: { temp: 29, condition: "Wet", waterTemp: null },
    11: { temp: 28, condition: "Wet", waterTemp: null },
    12: { temp: 27, condition: "Wet", waterTemp: null },
  },
  "Nusa Lembongan": {
    1: { temp: 27, condition: "Wet", waterTemp: 28 },
    2: { temp: 27, condition: "Wet", waterTemp: 28 },
    3: { temp: 28, condition: "Wet", waterTemp: 28 },
    4: { temp: 29, condition: "Humid", waterTemp: 29 },
    5: { temp: 28, condition: "Dry", waterTemp: 28 },
    6: { temp: 26, condition: "Dry & Cool", waterTemp: 27 },
    7: { temp: 25, condition: "Dry & Cool", waterTemp: 26 },
    8: { temp: 25, condition: "Dry & Cool", waterTemp: 26 },
    9: { temp: 26, condition: "Dry", waterTemp: 27 },
    10: { temp: 27, condition: "Dry", waterTemp: 28 },
    11: { temp: 27, condition: "Wet", waterTemp: 28 },
    12: { temp: 27, condition: "Wet", waterTemp: 28 },
  },
  "Bandung": {
    1: { temp: 22, condition: "Wet", waterTemp: null },
    2: { temp: 22, condition: "Wet", waterTemp: null },
    3: { temp: 23, condition: "Wet", waterTemp: null },
    4: { temp: 23, condition: "Humid", waterTemp: null },
    5: { temp: 23, condition: "Humid", waterTemp: null },
    6: { temp: 22, condition: "Dry", waterTemp: null },
    7: { temp: 21, condition: "Dry", waterTemp: null },
    8: { temp: 22, condition: "Dry", waterTemp: null },
    9: { temp: 22, condition: "Humid", waterTemp: null },
    10: { temp: 23, condition: "Wet", waterTemp: null },
    11: { temp: 23, condition: "Wet", waterTemp: null },
    12: { temp: 22, condition: "Wet", waterTemp: null },
  },
  "Bogor": {
    1: { temp: 25, condition: "Wet", waterTemp: null },
    2: { temp: 25, condition: "Wet", waterTemp: null },
    3: { temp: 26, condition: "Wet", waterTemp: null },
    4: { temp: 26, condition: "Wet", waterTemp: null },
    5: { temp: 26, condition: "Wet", waterTemp: null },
    6: { temp: 25, condition: "Humid", waterTemp: null },
    7: { temp: 24, condition: "Humid", waterTemp: null },
    8: { temp: 25, condition: "Humid", waterTemp: null },
    9: { temp: 25, condition: "Wet", waterTemp: null },
    10: { temp: 26, condition: "Wet", waterTemp: null },
    11: { temp: 25, condition: "Wet", waterTemp: null },
    12: { temp: 25, condition: "Wet", waterTemp: null },
  },
  "Bedugul": {
    1: { temp: 18, condition: "Wet", waterTemp: null },
    2: { temp: 18, condition: "Wet", waterTemp: null },
    3: { temp: 19, condition: "Wet", waterTemp: null },
    4: { temp: 20, condition: "Humid", waterTemp: null },
    5: { temp: 20, condition: "Dry", waterTemp: null },
    6: { temp: 19, condition: "Dry & Cool", waterTemp: null },
    7: { temp: 18, condition: "Dry & Cool", waterTemp: null },
    8: { temp: 18, condition: "Dry & Cool", waterTemp: null },
    9: { temp: 19, condition: "Dry", waterTemp: null },
    10: { temp: 20, condition: "Humid", waterTemp: null },
    11: { temp: 19, condition: "Wet", waterTemp: null },
    12: { temp: 18, condition: "Wet", waterTemp: null },
  },
  "Boyolali": {
    1: { temp: 23, condition: "Wet", waterTemp: null },
    2: { temp: 23, condition: "Wet", waterTemp: null },
    3: { temp: 24, condition: "Wet", waterTemp: null },
    4: { temp: 25, condition: "Humid", waterTemp: null },
    5: { temp: 25, condition: "Humid", waterTemp: null },
    6: { temp: 24, condition: "Dry", waterTemp: null },
    7: { temp: 23, condition: "Dry", waterTemp: null },
    8: { temp: 24, condition: "Dry", waterTemp: null },
    9: { temp: 24, condition: "Humid", waterTemp: null },
    10: { temp: 25, condition: "Wet", waterTemp: null },
    11: { temp: 24, condition: "Wet", waterTemp: null },
    12: { temp: 23, condition: "Wet", waterTemp: null },
  },
  "Surabaya": {
    1: { temp: 28, condition: "Wet", waterTemp: 29 },
    2: { temp: 28, condition: "Wet", waterTemp: 29 },
    3: { temp: 29, condition: "Wet", waterTemp: 29 },
    4: { temp: 30, condition: "Humid", waterTemp: 30 },
    5: { temp: 30, condition: "Dry", waterTemp: 30 },
    6: { temp: 29, condition: "Dry", waterTemp: 29 },
    7: { temp: 28, condition: "Dry", waterTemp: 28 },
    8: { temp: 28, condition: "Dry", waterTemp: 28 },
    9: { temp: 29, condition: "Dry", waterTemp: 29 },
    10: { temp: 30, condition: "Wet", waterTemp: 29 },
    11: { temp: 29, condition: "Wet", waterTemp: 29 },
    12: { temp: 28, condition: "Wet", waterTemp: 29 },
  },
  "Yogyakarta": {
    1: { temp: 26, condition: "Wet", waterTemp: null },
    2: { temp: 26, condition: "Wet", waterTemp: null },
    3: { temp: 27, condition: "Wet", waterTemp: null },
    4: { temp: 28, condition: "Humid", waterTemp: null },
    5: { temp: 28, condition: "Humid", waterTemp: null },
    6: { temp: 27, condition: "Dry", waterTemp: null },
    7: { temp: 26, condition: "Dry", waterTemp: null },
    8: { temp: 27, condition: "Dry", waterTemp: null },
    9: { temp: 27, condition: "Humid", waterTemp: null },
    10: { temp: 28, condition: "Wet", waterTemp: null },
    11: { temp: 27, condition: "Wet", waterTemp: null },
    12: { temp: 26, condition: "Wet", waterTemp: null },
  },
  "Bintan Island": {
    1: { temp: 27, condition: "Wet", waterTemp: 28 },
    2: { temp: 27, condition: "Wet", waterTemp: 28 },
    3: { temp: 28, condition: "Humid", waterTemp: 29 },
    4: { temp: 29, condition: "Hot", waterTemp: 29 },
    5: { temp: 29, condition: "Wet", waterTemp: 30 },
    6: { temp: 28, condition: "Wet", waterTemp: 29 },
    7: { temp: 28, condition: "Wet", waterTemp: 29 },
    8: { temp: 28, condition: "Wet", waterTemp: 29 },
    9: { temp: 28, condition: "Wet", waterTemp: 29 },
    10: { temp: 28, condition: "Wet", waterTemp: 29 },
    11: { temp: 27, condition: "Wet", waterTemp: 28 },
    12: { temp: 27, condition: "Wet", waterTemp: 28 },
  },
  "Lake Toba, North Sumatra": {
    1: { temp: 20, condition: "Wet", waterTemp: 22 },
    2: { temp: 20, condition: "Wet", waterTemp: 22 },
    3: { temp: 22, condition: "Wet", waterTemp: 22 },
    4: { temp: 22, condition: "Humid", waterTemp: 23 },
    5: { temp: 22, condition: "Humid", waterTemp: 23 },
    6: { temp: 22, condition: "Dry", waterTemp: 23 },
    7: { temp: 21, condition: "Dry", waterTemp: 22 },
    8: { temp: 22, condition: "Dry", waterTemp: 22 },
    9: { temp: 22, condition: "Humid", waterTemp: 22 },
    10: { temp: 22, condition: "Wet", waterTemp: 22 },
    11: { temp: 21, condition: "Wet", waterTemp: 22 },
    12: { temp: 20, condition: "Wet", waterTemp: 22 },
  },
  // ── MALAYSIA ──
  "Kuala Lumpur": {
    1: { temp: 28, condition: "Humid", waterTemp: null },
    2: { temp: 29, condition: "Humid", waterTemp: null },
    3: { temp: 30, condition: "Hot & Humid", waterTemp: null },
    4: { temp: 30, condition: "Hot & Humid", waterTemp: null },
    5: { temp: 30, condition: "Wet", waterTemp: null },
    6: { temp: 29, condition: "Wet", waterTemp: null },
    7: { temp: 29, condition: "Wet", waterTemp: null },
    8: { temp: 29, condition: "Wet", waterTemp: null },
    9: { temp: 29, condition: "Wet", waterTemp: null },
    10: { temp: 29, condition: "Wet", waterTemp: null },
    11: { temp: 28, condition: "Wet", waterTemp: null },
    12: { temp: 28, condition: "Wet", waterTemp: null },
  },
  "Putrajaya": {
    1: { temp: 28, condition: "Humid", waterTemp: null },
    2: { temp: 29, condition: "Humid", waterTemp: null },
    3: { temp: 30, condition: "Hot & Humid", waterTemp: null },
    4: { temp: 30, condition: "Hot & Humid", waterTemp: null },
    5: { temp: 30, condition: "Wet", waterTemp: null },
    6: { temp: 29, condition: "Wet", waterTemp: null },
    7: { temp: 29, condition: "Wet", waterTemp: null },
    8: { temp: 29, condition: "Wet", waterTemp: null },
    9: { temp: 29, condition: "Wet", waterTemp: null },
    10: { temp: 29, condition: "Wet", waterTemp: null },
    11: { temp: 28, condition: "Wet", waterTemp: null },
    12: { temp: 28, condition: "Wet", waterTemp: null },
  },
  "Penang": {
    1: { temp: 27, condition: "Dry", waterTemp: 28 },
    2: { temp: 28, condition: "Dry", waterTemp: 28 },
    3: { temp: 29, condition: "Hot", waterTemp: 29 },
    4: { temp: 30, condition: "Hot", waterTemp: 29 },
    5: { temp: 29, condition: "Wet", waterTemp: 29 },
    6: { temp: 28, condition: "Wet", waterTemp: 29 },
    7: { temp: 28, condition: "Wet", waterTemp: 29 },
    8: { temp: 28, condition: "Wet", waterTemp: 29 },
    9: { temp: 28, condition: "Wet", waterTemp: 28 },
    10: { temp: 28, condition: "Wet", waterTemp: 28 },
    11: { temp: 27, condition: "Wet", waterTemp: 28 },
    12: { temp: 27, condition: "Humid", waterTemp: 27 },
  },
  "Kota Kinabalu": {
    1: { temp: 27, condition: "Wet", waterTemp: 28 },
    2: { temp: 27, condition: "Wet", waterTemp: 28 },
    3: { temp: 28, condition: "Humid", waterTemp: 29 },
    4: { temp: 29, condition: "Hot", waterTemp: 29 },
    5: { temp: 29, condition: "Wet", waterTemp: 30 },
    6: { temp: 28, condition: "Wet", waterTemp: 29 },
    7: { temp: 28, condition: "Wet", waterTemp: 29 },
    8: { temp: 28, condition: "Wet", waterTemp: 29 },
    9: { temp: 28, condition: "Wet", waterTemp: 29 },
    10: { temp: 28, condition: "Wet", waterTemp: 28 },
    11: { temp: 27, condition: "Wet", waterTemp: 28 },
    12: { temp: 27, condition: "Wet", waterTemp: 28 },
  },
  "Kuching": {
    1: { temp: 27, condition: "Wet", waterTemp: null },
    2: { temp: 27, condition: "Wet", waterTemp: null },
    3: { temp: 28, condition: "Wet", waterTemp: null },
    4: { temp: 28, condition: "Humid", waterTemp: null },
    5: { temp: 28, condition: "Humid", waterTemp: null },
    6: { temp: 28, condition: "Wet", waterTemp: null },
    7: { temp: 27, condition: "Wet", waterTemp: null },
    8: { temp: 28, condition: "Wet", waterTemp: null },
    9: { temp: 28, condition: "Wet", waterTemp: null },
    10: { temp: 28, condition: "Wet", waterTemp: null },
    11: { temp: 27, condition: "Wet", waterTemp: null },
    12: { temp: 27, condition: "Wet", waterTemp: null },
  },
  "Langkawi": {
    1: { temp: 27, condition: "Dry", waterTemp: 28 },
    2: { temp: 28, condition: "Dry", waterTemp: 28 },
    3: { temp: 29, condition: "Hot", waterTemp: 29 },
    4: { temp: 30, condition: "Hot", waterTemp: 30 },
    5: { temp: 30, condition: "Wet", waterTemp: 30 },
    6: { temp: 29, condition: "Wet", waterTemp: 29 },
    7: { temp: 29, condition: "Wet", waterTemp: 29 },
    8: { temp: 29, condition: "Wet", waterTemp: 29 },
    9: { temp: 28, condition: "Wet", waterTemp: 29 },
    10: { temp: 28, condition: "Wet", waterTemp: 29 },
    11: { temp: 27, condition: "Wet", waterTemp: 28 },
    12: { temp: 27, condition: "Humid", waterTemp: 28 },
  },
  // ── SINGAPORE ──
  "Singapore": {
    1: { temp: 27, condition: "Wet", waterTemp: 28 },
    2: { temp: 28, condition: "Dry", waterTemp: 28 },
    3: { temp: 28, condition: "Dry", waterTemp: 29 },
    4: { temp: 29, condition: "Dry", waterTemp: 29 },
    5: { temp: 29, condition: "Wet", waterTemp: 30 },
    6: { temp: 29, condition: "Wet", waterTemp: 30 },
    7: { temp: 28, condition: "Wet", waterTemp: 29 },
    8: { temp: 28, condition: "Wet", waterTemp: 29 },
    9: { temp: 28, condition: "Wet", waterTemp: 29 },
    10: { temp: 28, condition: "Wet", waterTemp: 29 },
    11: { temp: 27, condition: "Wet", waterTemp: 28 },
    12: { temp: 27, condition: "Wet", waterTemp: 28 },
  },
  // ── SOUTH KOREA ──
  "Seoul": {
    1: { temp: -2, condition: "Cold & Dry", waterTemp: null },
    2: { temp: 1, condition: "Cold", waterTemp: null },
    3: { temp: 7, condition: "Cool", waterTemp: null },
    4: { temp: 14, condition: "Mild", waterTemp: null },
    5: { temp: 20, condition: "Mild", waterTemp: null },
    6: { temp: 24, condition: "Humid", waterTemp: null },
    7: { temp: 27, condition: "Hot & Wet", waterTemp: null },
    8: { temp: 28, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 23, condition: "Mild", waterTemp: null },
    10: { temp: 16, condition: "Cool", waterTemp: null },
    11: { temp: 8, condition: "Cool", waterTemp: null },
    12: { temp: 1, condition: "Cold", waterTemp: null },
  },
  "Busan": {
    1: { temp: 3, condition: "Cold", waterTemp: 11 },
    2: { temp: 5, condition: "Cold", waterTemp: 10 },
    3: { temp: 9, condition: "Cool", waterTemp: 11 },
    4: { temp: 15, condition: "Mild", waterTemp: 14 },
    5: { temp: 19, condition: "Mild", waterTemp: 17 },
    6: { temp: 23, condition: "Humid", waterTemp: 20 },
    7: { temp: 27, condition: "Hot & Wet", waterTemp: 24 },
    8: { temp: 28, condition: "Hot & Humid", waterTemp: 26 },
    9: { temp: 24, condition: "Mild", waterTemp: 24 },
    10: { temp: 18, condition: "Mild", waterTemp: 20 },
    11: { temp: 11, condition: "Cool", waterTemp: 16 },
    12: { temp: 5, condition: "Cold", waterTemp: 13 },
  },
  "Incheon": {
    1: { temp: -3, condition: "Cold", waterTemp: 5 },
    2: { temp: 0, condition: "Cold", waterTemp: 4 },
    3: { temp: 6, condition: "Cool", waterTemp: 6 },
    4: { temp: 13, condition: "Mild", waterTemp: 10 },
    5: { temp: 18, condition: "Mild", waterTemp: 14 },
    6: { temp: 23, condition: "Humid", waterTemp: 18 },
    7: { temp: 27, condition: "Hot & Wet", waterTemp: 22 },
    8: { temp: 28, condition: "Hot & Humid", waterTemp: 25 },
    9: { temp: 23, condition: "Mild", waterTemp: 22 },
    10: { temp: 16, condition: "Cool", waterTemp: 18 },
    11: { temp: 8, condition: "Cool", waterTemp: 13 },
    12: { temp: 1, condition: "Cold", waterTemp: 7 },
  },
  "Daegu": {
    1: { temp: -1, condition: "Cold", waterTemp: null },
    2: { temp: 2, condition: "Cold", waterTemp: null },
    3: { temp: 8, condition: "Cool", waterTemp: null },
    4: { temp: 15, condition: "Mild", waterTemp: null },
    5: { temp: 21, condition: "Mild", waterTemp: null },
    6: { temp: 25, condition: "Humid", waterTemp: null },
    7: { temp: 28, condition: "Hot & Wet", waterTemp: null },
    8: { temp: 29, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 24, condition: "Mild", waterTemp: null },
    10: { temp: 18, condition: "Cool", waterTemp: null },
    11: { temp: 10, condition: "Cool", waterTemp: null },
    12: { temp: 2, condition: "Cold", waterTemp: null },
  },
  "Jeju Island": {
    1: { temp: 6, condition: "Cool", waterTemp: 17 },
    2: { temp: 7, condition: "Cool", waterTemp: 16 },
    3: { temp: 10, condition: "Mild", waterTemp: 17 },
    4: { temp: 15, condition: "Mild", waterTemp: 18 },
    5: { temp: 20, condition: "Mild", waterTemp: 20 },
    6: { temp: 23, condition: "Humid", waterTemp: 22 },
    7: { temp: 27, condition: "Hot & Wet", waterTemp: 25 },
    8: { temp: 28, condition: "Hot & Humid", waterTemp: 27 },
    9: { temp: 24, condition: "Mild", waterTemp: 26 },
    10: { temp: 18, condition: "Mild", waterTemp: 23 },
    11: { temp: 12, condition: "Cool", waterTemp: 20 },
    12: { temp: 7, condition: "Cool", waterTemp: 18 },
  },
  "Jeju": {
    1: { temp: 6, condition: "Cool", waterTemp: 17 },
    2: { temp: 7, condition: "Cool", waterTemp: 16 },
    3: { temp: 10, condition: "Mild", waterTemp: 17 },
    4: { temp: 15, condition: "Mild", waterTemp: 18 },
    5: { temp: 20, condition: "Mild", waterTemp: 20 },
    6: { temp: 23, condition: "Humid", waterTemp: 22 },
    7: { temp: 27, condition: "Hot & Wet", waterTemp: 25 },
    8: { temp: 28, condition: "Hot & Humid", waterTemp: 27 },
    9: { temp: 24, condition: "Mild", waterTemp: 26 },
    10: { temp: 18, condition: "Mild", waterTemp: 23 },
    11: { temp: 12, condition: "Cool", waterTemp: 20 },
    12: { temp: 7, condition: "Cool", waterTemp: 18 },
  },
  // ── CHINA ──
  "Shanghai": {
    1: { temp: 4, condition: "Cold", waterTemp: null },
    2: { temp: 6, condition: "Cold", waterTemp: null },
    3: { temp: 10, condition: "Cool", waterTemp: null },
    4: { temp: 16, condition: "Mild", waterTemp: null },
    5: { temp: 22, condition: "Mild", waterTemp: null },
    6: { temp: 26, condition: "Humid", waterTemp: null },
    7: { temp: 30, condition: "Hot & Humid", waterTemp: null },
    8: { temp: 30, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 25, condition: "Humid", waterTemp: null },
    10: { temp: 19, condition: "Mild", waterTemp: null },
    11: { temp: 12, condition: "Cool", waterTemp: null },
    12: { temp: 6, condition: "Cold", waterTemp: null },
  },
  "Beijing": {
    1: { temp: -2, condition: "Cold & Dry", waterTemp: null },
    2: { temp: 1, condition: "Cold", waterTemp: null },
    3: { temp: 8, condition: "Cool", waterTemp: null },
    4: { temp: 16, condition: "Mild", waterTemp: null },
    5: { temp: 22, condition: "Warm", waterTemp: null },
    6: { temp: 27, condition: "Hot", waterTemp: null },
    7: { temp: 29, condition: "Hot & Wet", waterTemp: null },
    8: { temp: 28, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 22, condition: "Mild", waterTemp: null },
    10: { temp: 14, condition: "Cool", waterTemp: null },
    11: { temp: 5, condition: "Cool", waterTemp: null },
    12: { temp: -1, condition: "Cold", waterTemp: null },
  },
  "Hong Kong": {
    1: { temp: 16, condition: "Cool", waterTemp: 20 },
    2: { temp: 17, condition: "Cool & Humid", waterTemp: 19 },
    3: { temp: 20, condition: "Humid", waterTemp: 20 },
    4: { temp: 24, condition: "Humid", waterTemp: 22 },
    5: { temp: 28, condition: "Hot & Wet", waterTemp: 25 },
    6: { temp: 30, condition: "Hot & Wet", waterTemp: 27 },
    7: { temp: 31, condition: "Hot & Wet", waterTemp: 28 },
    8: { temp: 31, condition: "Hot & Wet", waterTemp: 29 },
    9: { temp: 29, condition: "Hot & Humid", waterTemp: 28 },
    10: { temp: 26, condition: "Mild", waterTemp: 26 },
    11: { temp: 22, condition: "Cool", waterTemp: 24 },
    12: { temp: 17, condition: "Cool", waterTemp: 21 },
  },
  "Guangzhou": {
    1: { temp: 14, condition: "Cool", waterTemp: null },
    2: { temp: 16, condition: "Cool & Humid", waterTemp: null },
    3: { temp: 20, condition: "Humid", waterTemp: null },
    4: { temp: 25, condition: "Humid", waterTemp: null },
    5: { temp: 29, condition: "Hot & Wet", waterTemp: null },
    6: { temp: 31, condition: "Hot & Wet", waterTemp: null },
    7: { temp: 32, condition: "Hot & Humid", waterTemp: null },
    8: { temp: 32, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 30, condition: "Humid", waterTemp: null },
    10: { temp: 26, condition: "Mild", waterTemp: null },
    11: { temp: 21, condition: "Cool", waterTemp: null },
    12: { temp: 15, condition: "Cool", waterTemp: null },
  },
  "Shenzhen": {
    1: { temp: 15, condition: "Cool", waterTemp: 19 },
    2: { temp: 17, condition: "Cool & Humid", waterTemp: 19 },
    3: { temp: 21, condition: "Humid", waterTemp: 20 },
    4: { temp: 25, condition: "Humid", waterTemp: 22 },
    5: { temp: 29, condition: "Hot & Wet", waterTemp: 25 },
    6: { temp: 31, condition: "Hot & Wet", waterTemp: 27 },
    7: { temp: 32, condition: "Hot & Humid", waterTemp: 28 },
    8: { temp: 32, condition: "Hot & Humid", waterTemp: 29 },
    9: { temp: 30, condition: "Humid", waterTemp: 28 },
    10: { temp: 26, condition: "Mild", waterTemp: 26 },
    11: { temp: 21, condition: "Cool", waterTemp: 23 },
    12: { temp: 16, condition: "Cool", waterTemp: 21 },
  },
  "Sanya": {
    1: { temp: 21, condition: "Dry", waterTemp: 24 },
    2: { temp: 22, condition: "Dry", waterTemp: 24 },
    3: { temp: 25, condition: "Mild", waterTemp: 25 },
    4: { temp: 28, condition: "Hot", waterTemp: 27 },
    5: { temp: 30, condition: "Hot & Humid", waterTemp: 28 },
    6: { temp: 31, condition: "Wet", waterTemp: 29 },
    7: { temp: 31, condition: "Wet", waterTemp: 30 },
    8: { temp: 31, condition: "Wet", waterTemp: 30 },
    9: { temp: 30, condition: "Wet", waterTemp: 29 },
    10: { temp: 28, condition: "Humid", waterTemp: 28 },
    11: { temp: 25, condition: "Dry", waterTemp: 27 },
    12: { temp: 22, condition: "Dry", waterTemp: 25 },
  },
  "Haikou": {
    1: { temp: 18, condition: "Cool", waterTemp: 21 },
    2: { temp: 19, condition: "Mild", waterTemp: 21 },
    3: { temp: 23, condition: "Mild", waterTemp: 23 },
    4: { temp: 27, condition: "Hot", waterTemp: 25 },
    5: { temp: 30, condition: "Hot & Humid", waterTemp: 27 },
    6: { temp: 31, condition: "Wet", waterTemp: 28 },
    7: { temp: 31, condition: "Wet", waterTemp: 29 },
    8: { temp: 31, condition: "Wet", waterTemp: 29 },
    9: { temp: 30, condition: "Wet", waterTemp: 28 },
    10: { temp: 27, condition: "Humid", waterTemp: 27 },
    11: { temp: 23, condition: "Cool", waterTemp: 25 },
    12: { temp: 19, condition: "Cool", waterTemp: 22 },
  },
  "Nanning": {
    1: { temp: 13, condition: "Cool", waterTemp: null },
    2: { temp: 15, condition: "Cool & Humid", waterTemp: null },
    3: { temp: 19, condition: "Humid", waterTemp: null },
    4: { temp: 24, condition: "Humid", waterTemp: null },
    5: { temp: 28, condition: "Hot & Wet", waterTemp: null },
    6: { temp: 30, condition: "Hot & Wet", waterTemp: null },
    7: { temp: 31, condition: "Hot & Humid", waterTemp: null },
    8: { temp: 31, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 29, condition: "Humid", waterTemp: null },
    10: { temp: 25, condition: "Mild", waterTemp: null },
    11: { temp: 19, condition: "Cool", waterTemp: null },
    12: { temp: 14, condition: "Cool", waterTemp: null },
  },
  "Chongqing": {
    1: { temp: 8, condition: "Cool", waterTemp: null },
    2: { temp: 10, condition: "Cool", waterTemp: null },
    3: { temp: 15, condition: "Mild", waterTemp: null },
    4: { temp: 21, condition: "Mild", waterTemp: null },
    5: { temp: 25, condition: "Humid", waterTemp: null },
    6: { temp: 28, condition: "Hot & Wet", waterTemp: null },
    7: { temp: 33, condition: "Hot & Humid", waterTemp: null },
    8: { temp: 34, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 28, condition: "Humid", waterTemp: null },
    10: { temp: 21, condition: "Mild", waterTemp: null },
    11: { temp: 14, condition: "Cool", waterTemp: null },
    12: { temp: 9, condition: "Cool", waterTemp: null },
  },
  "Hangzhou": {
    1: { temp: 5, condition: "Cold", waterTemp: null },
    2: { temp: 7, condition: "Cold", waterTemp: null },
    3: { temp: 12, condition: "Cool", waterTemp: null },
    4: { temp: 18, condition: "Mild", waterTemp: null },
    5: { temp: 23, condition: "Mild", waterTemp: null },
    6: { temp: 27, condition: "Humid", waterTemp: null },
    7: { temp: 31, condition: "Hot & Humid", waterTemp: null },
    8: { temp: 31, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 26, condition: "Humid", waterTemp: null },
    10: { temp: 20, condition: "Mild", waterTemp: null },
    11: { temp: 13, condition: "Cool", waterTemp: null },
    12: { temp: 6, condition: "Cold", waterTemp: null },
  },
  "Wuhan": {
    1: { temp: 4, condition: "Cold", waterTemp: null },
    2: { temp: 6, condition: "Cold", waterTemp: null },
    3: { temp: 12, condition: "Cool", waterTemp: null },
    4: { temp: 19, condition: "Mild", waterTemp: null },
    5: { temp: 24, condition: "Mild", waterTemp: null },
    6: { temp: 28, condition: "Humid", waterTemp: null },
    7: { temp: 32, condition: "Hot & Humid", waterTemp: null },
    8: { temp: 32, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 27, condition: "Humid", waterTemp: null },
    10: { temp: 20, condition: "Mild", waterTemp: null },
    11: { temp: 13, condition: "Cool", waterTemp: null },
    12: { temp: 6, condition: "Cold", waterTemp: null },
  },
  "Hefei": {
    1: { temp: 3, condition: "Cold", waterTemp: null },
    2: { temp: 5, condition: "Cold", waterTemp: null },
    3: { temp: 11, condition: "Cool", waterTemp: null },
    4: { temp: 17, condition: "Mild", waterTemp: null },
    5: { temp: 23, condition: "Mild", waterTemp: null },
    6: { temp: 27, condition: "Humid", waterTemp: null },
    7: { temp: 31, condition: "Hot & Humid", waterTemp: null },
    8: { temp: 31, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 26, condition: "Humid", waterTemp: null },
    10: { temp: 19, condition: "Mild", waterTemp: null },
    11: { temp: 12, condition: "Cool", waterTemp: null },
    12: { temp: 5, condition: "Cold", waterTemp: null },
  },
  "Qingdao": {
    1: { temp: 0, condition: "Cold", waterTemp: 7 },
    2: { temp: 2, condition: "Cold", waterTemp: 6 },
    3: { temp: 7, condition: "Cool", waterTemp: 8 },
    4: { temp: 13, condition: "Mild", waterTemp: 11 },
    5: { temp: 18, condition: "Mild", waterTemp: 15 },
    6: { temp: 23, condition: "Humid", waterTemp: 19 },
    7: { temp: 26, condition: "Hot & Wet", waterTemp: 24 },
    8: { temp: 27, condition: "Hot & Humid", waterTemp: 26 },
    9: { temp: 22, condition: "Mild", waterTemp: 24 },
    10: { temp: 16, condition: "Cool", waterTemp: 20 },
    11: { temp: 9, condition: "Cool", waterTemp: 14 },
    12: { temp: 2, condition: "Cold", waterTemp: 9 },
  },
  "Dalian": {
    1: { temp: -5, condition: "Cold", waterTemp: 4 },
    2: { temp: -3, condition: "Cold", waterTemp: 3 },
    3: { temp: 4, condition: "Cool", waterTemp: 5 },
    4: { temp: 11, condition: "Mild", waterTemp: 8 },
    5: { temp: 17, condition: "Mild", waterTemp: 12 },
    6: { temp: 21, condition: "Humid", waterTemp: 17 },
    7: { temp: 25, condition: "Hot & Wet", waterTemp: 22 },
    8: { temp: 26, condition: "Hot & Humid", waterTemp: 24 },
    9: { temp: 21, condition: "Mild", waterTemp: 22 },
    10: { temp: 14, condition: "Cool", waterTemp: 18 },
    11: { temp: 5, condition: "Cool", waterTemp: 12 },
    12: { temp: -2, condition: "Cold", waterTemp: 7 },
  },
  "Tianjin": {
    1: { temp: -4, condition: "Cold", waterTemp: null },
    2: { temp: -1, condition: "Cold", waterTemp: null },
    3: { temp: 6, condition: "Cool", waterTemp: null },
    4: { temp: 14, condition: "Mild", waterTemp: null },
    5: { temp: 21, condition: "Mild", waterTemp: null },
    6: { temp: 26, condition: "Humid", waterTemp: null },
    7: { temp: 29, condition: "Hot & Wet", waterTemp: null },
    8: { temp: 28, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 23, condition: "Mild", waterTemp: null },
    10: { temp: 15, condition: "Cool", waterTemp: null },
    11: { temp: 6, condition: "Cool", waterTemp: null },
    12: { temp: -2, condition: "Cold", waterTemp: null },
  },
  "Shenyang": {
    1: { temp: -13, condition: "Cold", waterTemp: null },
    2: { temp: -9, condition: "Cold", waterTemp: null },
    3: { temp: 0, condition: "Cold", waterTemp: null },
    4: { temp: 10, condition: "Cool", waterTemp: null },
    5: { temp: 18, condition: "Mild", waterTemp: null },
    6: { temp: 24, condition: "Humid", waterTemp: null },
    7: { temp: 27, condition: "Hot & Wet", waterTemp: null },
    8: { temp: 26, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 20, condition: "Mild", waterTemp: null },
    10: { temp: 11, condition: "Cool", waterTemp: null },
    11: { temp: 1, condition: "Cold", waterTemp: null },
    12: { temp: -9, condition: "Cold", waterTemp: null },
  },
  "Harbin": {
    1: { temp: -18, condition: "Cold", waterTemp: null },
    2: { temp: -14, condition: "Cold", waterTemp: null },
    3: { temp: -4, condition: "Cold", waterTemp: null },
    4: { temp: 8, condition: "Cool", waterTemp: null },
    5: { temp: 16, condition: "Mild", waterTemp: null },
    6: { temp: 22, condition: "Humid", waterTemp: null },
    7: { temp: 26, condition: "Hot & Wet", waterTemp: null },
    8: { temp: 24, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 17, condition: "Mild", waterTemp: null },
    10: { temp: 7, condition: "Cool", waterTemp: null },
    11: { temp: -5, condition: "Cold", waterTemp: null },
    12: { temp: -15, condition: "Cold", waterTemp: null },
  },
  "Kunming": {
    1: { temp: 9, condition: "Dry", waterTemp: null },
    2: { temp: 11, condition: "Dry", waterTemp: null },
    3: { temp: 16, condition: "Dry", waterTemp: null },
    4: { temp: 19, condition: "Mild", waterTemp: null },
    5: { temp: 21, condition: "Mild", waterTemp: null },
    6: { temp: 20, condition: "Wet", waterTemp: null },
    7: { temp: 20, condition: "Wet", waterTemp: null },
    8: { temp: 20, condition: "Wet", waterTemp: null },
    9: { temp: 19, condition: "Wet", waterTemp: null },
    10: { temp: 16, condition: "Mild", waterTemp: null },
    11: { temp: 12, condition: "Cool", waterTemp: null },
    12: { temp: 9, condition: "Dry", waterTemp: null },
  },
  "Dali": {
    1: { temp: 9, condition: "Dry", waterTemp: null },
    2: { temp: 12, condition: "Dry", waterTemp: null },
    3: { temp: 16, condition: "Dry", waterTemp: null },
    4: { temp: 19, condition: "Mild", waterTemp: null },
    5: { temp: 21, condition: "Mild", waterTemp: null },
    6: { temp: 20, condition: "Wet", waterTemp: null },
    7: { temp: 20, condition: "Wet", waterTemp: null },
    8: { temp: 20, condition: "Wet", waterTemp: null },
    9: { temp: 19, condition: "Wet", waterTemp: null },
    10: { temp: 16, condition: "Mild", waterTemp: null },
    11: { temp: 12, condition: "Cool", waterTemp: null },
    12: { temp: 9, condition: "Dry", waterTemp: null },
  },
  "Lhasa": {
    1: { temp: -2, condition: "Cold & Dry", waterTemp: null },
    2: { temp: 1, condition: "Cold & Dry", waterTemp: null },
    3: { temp: 5, condition: "Cool", waterTemp: null },
    4: { temp: 9, condition: "Mild", waterTemp: null },
    5: { temp: 13, condition: "Mild", waterTemp: null },
    6: { temp: 15, condition: "Wet", waterTemp: null },
    7: { temp: 15, condition: "Wet", waterTemp: null },
    8: { temp: 15, condition: "Wet", waterTemp: null },
    9: { temp: 13, condition: "Wet", waterTemp: null },
    10: { temp: 7, condition: "Cool & Dry", waterTemp: null },
    11: { temp: 1, condition: "Cold", waterTemp: null },
    12: { temp: -3, condition: "Cold & Dry", waterTemp: null },
  },
  "Xi'an": {
    1: { temp: 2, condition: "Cold", waterTemp: null },
    2: { temp: 5, condition: "Cold", waterTemp: null },
    3: { temp: 11, condition: "Cool", waterTemp: null },
    4: { temp: 18, condition: "Mild", waterTemp: null },
    5: { temp: 23, condition: "Mild", waterTemp: null },
    6: { temp: 28, condition: "Hot", waterTemp: null },
    7: { temp: 30, condition: "Hot & Wet", waterTemp: null },
    8: { temp: 29, condition: "Hot & Humid", waterTemp: null },
    9: { temp: 23, condition: "Mild", waterTemp: null },
    10: { temp: 16, condition: "Cool", waterTemp: null },
    11: { temp: 8, condition: "Cool", waterTemp: null },
    12: { temp: 2, condition: "Cold", waterTemp: null },
  },
  // ── TAIWAN ──
  "Taipei": {
    1: { temp: 15, condition: "Cool & Wet", waterTemp: null },
    2: { temp: 16, condition: "Cool & Wet", waterTemp: null },
    3: { temp: 19, condition: "Mild & Wet", waterTemp: null },
    4: { temp: 23, condition: "Mild", waterTemp: null },
    5: { temp: 27, condition: "Warm", waterTemp: null },
    6: { temp: 30, condition: "Hot & Wet", waterTemp: null },
    7: { temp: 33, condition: "Hot", waterTemp: null },
    8: { temp: 33, condition: "Hot", waterTemp: null },
    9: { temp: 29, condition: "Humid", waterTemp: null },
    10: { temp: 25, condition: "Mild", waterTemp: null },
    11: { temp: 20, condition: "Cool", waterTemp: null },
    12: { temp: 16, condition: "Cool", waterTemp: null },
  },
  "Penghu": {
    1: { temp: 15, condition: "Cool & Windy", waterTemp: 22 },
    2: { temp: 15, condition: "Cool & Windy", waterTemp: 21 },
    3: { temp: 18, condition: "Mild", waterTemp: 22 },
    4: { temp: 22, condition: "Mild", waterTemp: 23 },
    5: { temp: 26, condition: "Warm", waterTemp: 25 },
    6: { temp: 29, condition: "Hot", waterTemp: 27 },
    7: { temp: 31, condition: "Hot", waterTemp: 28 },
    8: { temp: 31, condition: "Hot", waterTemp: 29 },
    9: { temp: 28, condition: "Humid", waterTemp: 28 },
    10: { temp: 24, condition: "Mild", waterTemp: 27 },
    11: { temp: 20, condition: "Cool", waterTemp: 25 },
    12: { temp: 16, condition: "Cool & Windy", waterTemp: 23 },
  },
  // ── NEPAL ──
  "Namche Bazaar": {
    1: { temp: -4, condition: "Cold & Dry", waterTemp: null },
    2: { temp: -2, condition: "Cold", waterTemp: null },
    3: { temp: 2, condition: "Cool", waterTemp: null },
    4: { temp: 7, condition: "Mild", waterTemp: null },
    5: { temp: 10, condition: "Mild & Wet", waterTemp: null },
    6: { temp: 13, condition: "Wet", waterTemp: null },
    7: { temp: 14, condition: "Wet", waterTemp: null },
    8: { temp: 14, condition: "Wet", waterTemp: null },
    9: { temp: 11, condition: "Wet", waterTemp: null },
    10: { temp: 5, condition: "Cool & Dry", waterTemp: null },
    11: { temp: -1, condition: "Cold", waterTemp: null },
    12: { temp: -4, condition: "Cold & Dry", waterTemp: null },
  },
  "Namche Bazaar, Nepal": {
    1: { temp: -4, condition: "Cold & Dry", waterTemp: null },
    2: { temp: -2, condition: "Cold", waterTemp: null },
    3: { temp: 2, condition: "Cool", waterTemp: null },
    4: { temp: 7, condition: "Mild", waterTemp: null },
    5: { temp: 10, condition: "Mild & Wet", waterTemp: null },
    6: { temp: 13, condition: "Wet", waterTemp: null },
    7: { temp: 14, condition: "Wet", waterTemp: null },
    8: { temp: 14, condition: "Wet", waterTemp: null },
    9: { temp: 11, condition: "Wet", waterTemp: null },
    10: { temp: 5, condition: "Cool & Dry", waterTemp: null },
    11: { temp: -1, condition: "Cold", waterTemp: null },
    12: { temp: -4, condition: "Cold & Dry", waterTemp: null },
  },
  "Kathmandu": {
    1: { temp: 8, condition: "Cold", waterTemp: null },
    2: { temp: 10, condition: "Cool", waterTemp: null },
    3: { temp: 15, condition: "Mild", waterTemp: null },
    4: { temp: 19, condition: "Mild", waterTemp: null },
    5: { temp: 22, condition: "Humid", waterTemp: null },
    6: { temp: 24, condition: "Wet", waterTemp: null },
    7: { temp: 24, condition: "Wet", waterTemp: null },
    8: { temp: 24, condition: "Wet", waterTemp: null },
    9: { temp: 22, condition: "Wet", waterTemp: null },
    10: { temp: 18, condition: "Mild", waterTemp: null },
    11: { temp: 13, condition: "Cool", waterTemp: null },
    12: { temp: 8, condition: "Cold", waterTemp: null },
  },
  "Pokhara": {
    1: { temp: 10, condition: "Cold", waterTemp: null },
    2: { temp: 12, condition: "Cool", waterTemp: null },
    3: { temp: 17, condition: "Mild", waterTemp: null },
    4: { temp: 21, condition: "Mild", waterTemp: null },
    5: { temp: 23, condition: "Humid", waterTemp: null },
    6: { temp: 24, condition: "Wet", waterTemp: null },
    7: { temp: 24, condition: "Wet", waterTemp: null },
    8: { temp: 24, condition: "Wet", waterTemp: null },
    9: { temp: 23, condition: "Wet", waterTemp: null },
    10: { temp: 19, condition: "Mild", waterTemp: null },
    11: { temp: 14, condition: "Cool", waterTemp: null },
    12: { temp: 10, condition: "Cold", waterTemp: null },
  },
  // ── SRI LANKA ──
  "Colombo": {
    1: { temp: 27, condition: "Dry", waterTemp: 28 },
    2: { temp: 28, condition: "Dry", waterTemp: 28 },
    3: { temp: 29, condition: "Hot", waterTemp: 29 },
    4: { temp: 30, condition: "Hot & Wet", waterTemp: 30 },
    5: { temp: 29, condition: "Wet", waterTemp: 30 },
    6: { temp: 28, condition: "Wet", waterTemp: 29 },
    7: { temp: 28, condition: "Wet", waterTemp: 28 },
    8: { temp: 28, condition: "Wet", waterTemp: 28 },
    9: { temp: 28, condition: "Wet", waterTemp: 28 },
    10: { temp: 28, condition: "Wet", waterTemp: 28 },
    11: { temp: 27, condition: "Wet", waterTemp: 28 },
    12: { temp: 27, condition: "Dry", waterTemp: 27 },
  },
  // ── MALDIVES ──
  "Malé": {
    1: { temp: 28, condition: "Dry", waterTemp: 29 },
    2: { temp: 28, condition: "Dry", waterTemp: 29 },
    3: { temp: 29, condition: "Hot & Dry", waterTemp: 29 },
    4: { temp: 29, condition: "Hot", waterTemp: 30 },
    5: { temp: 29, condition: "Wet", waterTemp: 30 },
    6: { temp: 28, condition: "Wet", waterTemp: 29 },
    7: { temp: 28, condition: "Wet", waterTemp: 29 },
    8: { temp: 28, condition: "Wet", waterTemp: 29 },
    9: { temp: 28, condition: "Wet", waterTemp: 29 },
    10: { temp: 28, condition: "Wet", waterTemp: 29 },
    11: { temp: 28, condition: "Dry", waterTemp: 29 },
    12: { temp: 28, condition: "Dry", waterTemp: 29 },
  },
  // ── CAMBODIA ──
  "Siem Reap": {
    1: { temp: 26, condition: "Dry", waterTemp: null },
    2: { temp: 28, condition: "Dry", waterTemp: null },
    3: { temp: 30, condition: "Hot", waterTemp: null },
    4: { temp: 32, condition: "Hot", waterTemp: null },
    5: { temp: 30, condition: "Wet", waterTemp: null },
    6: { temp: 29, condition: "Wet", waterTemp: null },
    7: { temp: 28, condition: "Wet", waterTemp: null },
    8: { temp: 28, condition: "Wet", waterTemp: null },
    9: { temp: 28, condition: "Wet", waterTemp: null },
    10: { temp: 27, condition: "Wet", waterTemp: null },
    11: { temp: 27, condition: "Dry", waterTemp: null },
    12: { temp: 25, condition: "Dry", waterTemp: null },
  },
  // ── MYANMAR ──
  "Bagan": {
    1: { temp: 22, condition: "Dry & Cool", waterTemp: null },
    2: { temp: 25, condition: "Dry", waterTemp: null },
    3: { temp: 30, condition: "Hot", waterTemp: null },
    4: { temp: 34, condition: "Hot", waterTemp: null },
    5: { temp: 33, condition: "Hot", waterTemp: null },
    6: { temp: 30, condition: "Wet", waterTemp: null },
    7: { temp: 29, condition: "Wet", waterTemp: null },
    8: { temp: 29, condition: "Wet", waterTemp: null },
    9: { temp: 29, condition: "Wet", waterTemp: null },
    10: { temp: 28, condition: "Humid", waterTemp: null },
    11: { temp: 25, condition: "Dry", waterTemp: null },
    12: { temp: 21, condition: "Dry & Cool", waterTemp: null },
  },
  // ── BANGLADESH ──
  "Dhaka": {
    1: { temp: 18, condition: "Dry", waterTemp: null },
    2: { temp: 21, condition: "Dry", waterTemp: null },
    3: { temp: 27, condition: "Hot", waterTemp: null },
    4: { temp: 30, condition: "Hot", waterTemp: null },
    5: { temp: 31, condition: "Hot & Humid", waterTemp: null },
    6: { temp: 30, condition: "Wet", waterTemp: null },
    7: { temp: 29, condition: "Wet", waterTemp: null },
    8: { temp: 29, condition: "Wet", waterTemp: null },
    9: { temp: 29, condition: "Wet", waterTemp: null },
    10: { temp: 27, condition: "Humid", waterTemp: null },
    11: { temp: 23, condition: "Dry", waterTemp: null },
    12: { temp: 18, condition: "Dry", waterTemp: null },
  },
  // ── MONGOLIA ──
  "Gobi Desert": {
    1: { temp: -15, condition: "Extreme Cold", waterTemp: null },
    2: { temp: -10, condition: "Cold", waterTemp: null },
    3: { temp: -1, condition: "Cold & Windy", waterTemp: null },
    4: { temp: 9, condition: "Cool & Windy", waterTemp: null },
    5: { temp: 18, condition: "Warm", waterTemp: null },
    6: { temp: 24, condition: "Hot & Dry", waterTemp: null },
    7: { temp: 26, condition: "Hot & Dry", waterTemp: null },
    8: { temp: 24, condition: "Hot & Dry", waterTemp: null },
    9: { temp: 15, condition: "Cool", waterTemp: null },
    10: { temp: 5, condition: "Cold", waterTemp: null },
    11: { temp: -6, condition: "Cold", waterTemp: null },
    12: { temp: -13, condition: "Extreme Cold", waterTemp: null },
  },
  "Ulaanbaatar": {
    1: { temp: -22, condition: "Cold", waterTemp: null },
    2: { temp: -17, condition: "Cold", waterTemp: null },
    3: { temp: -7, condition: "Cold", waterTemp: null },
    4: { temp: 4, condition: "Cool", waterTemp: null },
    5: { temp: 13, condition: "Mild", waterTemp: null },
    6: { temp: 19, condition: "Mild", waterTemp: null },
    7: { temp: 22, condition: "Warm", waterTemp: null },
    8: { temp: 21, condition: "Mild", waterTemp: null },
    9: { temp: 13, condition: "Cool", waterTemp: null },
    10: { temp: 2, condition: "Cool", waterTemp: null },
    11: { temp: -11, condition: "Cold", waterTemp: null },
    12: { temp: -19, condition: "Cold", waterTemp: null },
  },
  // ── BHUTAN ──
  "Thimphu": {
    1: { temp: 5, condition: "Cold & Dry", waterTemp: null },
    2: { temp: 7, condition: "Cold", waterTemp: null },
    3: { temp: 12, condition: "Mild", waterTemp: null },
    4: { temp: 16, condition: "Mild", waterTemp: null },
    5: { temp: 19, condition: "Mild & Wet", waterTemp: null },
    6: { temp: 21, condition: "Wet", waterTemp: null },
    7: { temp: 21, condition: "Wet", waterTemp: null },
    8: { temp: 21, condition: "Wet", waterTemp: null },
    9: { temp: 19, condition: "Wet", waterTemp: null },
    10: { temp: 14, condition: "Cool & Dry", waterTemp: null },
    11: { temp: 9, condition: "Cool", waterTemp: null },
    12: { temp: 5, condition: "Cold", waterTemp: null },
  },
  // ── LAOS ──
  "Luang Prabang": {
    1: { temp: 20, condition: "Dry & Cool", waterTemp: null },
    2: { temp: 23, condition: "Dry", waterTemp: null },
    3: { temp: 27, condition: "Hot", waterTemp: null },
    4: { temp: 30, condition: "Hot", waterTemp: null },
    5: { temp: 28, condition: "Wet", waterTemp: null },
    6: { temp: 27, condition: "Wet", waterTemp: null },
    7: { temp: 27, condition: "Wet", waterTemp: null },
    8: { temp: 27, condition: "Wet", waterTemp: null },
    9: { temp: 26, condition: "Wet", waterTemp: null },
    10: { temp: 25, condition: "Dry", waterTemp: null },
    11: { temp: 22, condition: "Dry", waterTemp: null },
    12: { temp: 19, condition: "Dry & Cool", waterTemp: null },
  },
  // ── UAE ──
  "Dubai": {
    1: { temp: 19, condition: "Mild & Dry", waterTemp: 22 },
    2: { temp: 21, condition: "Mild", waterTemp: 22 },
    3: { temp: 25, condition: "Warm", waterTemp: 24 },
    4: { temp: 30, condition: "Hot", waterTemp: 26 },
    5: { temp: 35, condition: "Hot", waterTemp: 28 },
    6: { temp: 38, condition: "Extreme Heat", waterTemp: 30 },
    7: { temp: 40, condition: "Extreme Heat", waterTemp: 32 },
    8: { temp: 40, condition: "Extreme Heat", waterTemp: 33 },
    9: { temp: 37, condition: "Hot", waterTemp: 32 },
    10: { temp: 32, condition: "Hot", waterTemp: 29 },
    11: { temp: 26, condition: "Warm", waterTemp: 26 },
    12: { temp: 21, condition: "Mild", waterTemp: 23 },
  },
  "Abu Dhabi": {
    1: { temp: 19, condition: "Mild", waterTemp: 22 },
    2: { temp: 21, condition: "Mild", waterTemp: 22 },
    3: { temp: 26, condition: "Warm", waterTemp: 24 },
    4: { temp: 31, condition: "Hot", waterTemp: 27 },
    5: { temp: 36, condition: "Hot", waterTemp: 29 },
    6: { temp: 38, condition: "Extreme Heat", waterTemp: 31 },
    7: { temp: 40, condition: "Extreme Heat", waterTemp: 33 },
    8: { temp: 40, condition: "Extreme Heat", waterTemp: 34 },
    9: { temp: 37, condition: "Hot", waterTemp: 33 },
    10: { temp: 33, condition: "Hot", waterTemp: 30 },
    11: { temp: 27, condition: "Warm", waterTemp: 27 },
    12: { temp: 21, condition: "Mild", waterTemp: 23 },
  },
  // ── BAHRAIN ──
  "Bahrain": {
    1: { temp: 17, condition: "Mild", waterTemp: 20 },
    2: { temp: 19, condition: "Mild", waterTemp: 20 },
    3: { temp: 24, condition: "Warm", waterTemp: 22 },
    4: { temp: 30, condition: "Hot", waterTemp: 25 },
    5: { temp: 35, condition: "Hot", waterTemp: 28 },
    6: { temp: 38, condition: "Extreme Heat", waterTemp: 31 },
    7: { temp: 40, condition: "Extreme Heat", waterTemp: 33 },
    8: { temp: 40, condition: "Extreme Heat", waterTemp: 34 },
    9: { temp: 37, condition: "Hot", waterTemp: 33 },
    10: { temp: 32, condition: "Hot", waterTemp: 30 },
    11: { temp: 25, condition: "Warm", waterTemp: 26 },
    12: { temp: 19, condition: "Mild", waterTemp: 21 },
  },
  // ── UZBEKISTAN ──
  "Tashkent": {
    1: { temp: 2, condition: "Cold", waterTemp: null },
    2: { temp: 5, condition: "Cold", waterTemp: null },
    3: { temp: 12, condition: "Cool", waterTemp: null },
    4: { temp: 19, condition: "Mild", waterTemp: null },
    5: { temp: 25, condition: "Warm", waterTemp: null },
    6: { temp: 30, condition: "Hot", waterTemp: null },
    7: { temp: 33, condition: "Hot", waterTemp: null },
    8: { temp: 32, condition: "Hot", waterTemp: null },
    9: { temp: 26, condition: "Warm", waterTemp: null },
    10: { temp: 18, condition: "Mild", waterTemp: null },
    11: { temp: 10, condition: "Cool", waterTemp: null },
    12: { temp: 4, condition: "Cold", waterTemp: null },
  },
  "Samarkand": {
    1: { temp: 1, condition: "Cold", waterTemp: null },
    2: { temp: 4, condition: "Cold", waterTemp: null },
    3: { temp: 11, condition: "Cool", waterTemp: null },
    4: { temp: 18, condition: "Mild", waterTemp: null },
    5: { temp: 24, condition: "Warm", waterTemp: null },
    6: { temp: 30, condition: "Hot", waterTemp: null },
    7: { temp: 33, condition: "Hot", waterTemp: null },
    8: { temp: 31, condition: "Hot", waterTemp: null },
    9: { temp: 25, condition: "Warm", waterTemp: null },
    10: { temp: 17, condition: "Mild", waterTemp: null },
    11: { temp: 9, condition: "Cool", waterTemp: null },
    12: { temp: 3, condition: "Cold", waterTemp: null },
  },
  "Bukhara": {
    1: { temp: 2, condition: "Cold", waterTemp: null },
    2: { temp: 5, condition: "Cold", waterTemp: null },
    3: { temp: 13, condition: "Cool", waterTemp: null },
    4: { temp: 20, condition: "Mild", waterTemp: null },
    5: { temp: 26, condition: "Hot", waterTemp: null },
    6: { temp: 32, condition: "Hot", waterTemp: null },
    7: { temp: 36, condition: "Hot", waterTemp: null },
    8: { temp: 34, condition: "Hot", waterTemp: null },
    9: { temp: 27, condition: "Warm", waterTemp: null },
    10: { temp: 18, condition: "Mild", waterTemp: null },
    11: { temp: 10, condition: "Cool", waterTemp: null },
    12: { temp: 3, condition: "Cold", waterTemp: null },
  },
  // ── NEW ZEALAND ──
  "Auckland": {
    1: { temp: 23, condition: "Warm", waterTemp: 21 },
    2: { temp: 23, condition: "Warm", waterTemp: 21 },
    3: { temp: 21, condition: "Mild", waterTemp: 20 },
    4: { temp: 18, condition: "Mild", waterTemp: 18 },
    5: { temp: 15, condition: "Cool", waterTemp: 16 },
    6: { temp: 13, condition: "Cool & Wet", waterTemp: 14 },
    7: { temp: 12, condition: "Cool & Wet", waterTemp: 13 },
    8: { temp: 12, condition: "Cool", waterTemp: 13 },
    9: { temp: 14, condition: "Mild", waterTemp: 14 },
    10: { temp: 16, condition: "Mild", waterTemp: 15 },
    11: { temp: 18, condition: "Mild", waterTemp: 17 },
    12: { temp: 21, condition: "Warm", waterTemp: 19 },
  },
  "Wellington": {
    1: { temp: 18, condition: "Mild", waterTemp: 17 },
    2: { temp: 18, condition: "Mild", waterTemp: 17 },
    3: { temp: 17, condition: "Mild", waterTemp: 16 },
    4: { temp: 14, condition: "Cool", waterTemp: 14 },
    5: { temp: 12, condition: "Cool", waterTemp: 12 },
    6: { temp: 10, condition: "Cool & Wet", waterTemp: 11 },
    7: { temp: 9, condition: "Cool & Wet", waterTemp: 10 },
    8: { temp: 10, condition: "Cool", waterTemp: 10 },
    9: { temp: 11, condition: "Mild", waterTemp: 11 },
    10: { temp: 13, condition: "Mild", waterTemp: 12 },
    11: { temp: 15, condition: "Mild", waterTemp: 14 },
    12: { temp: 17, condition: "Mild", waterTemp: 16 },
  },
  // ── AUSTRALIA ──
  "Sydney": {
    1: { temp: 26, condition: "Hot", waterTemp: 23 },
    2: { temp: 26, condition: "Hot", waterTemp: 23 },
    3: { temp: 24, condition: "Mild", waterTemp: 22 },
    4: { temp: 21, condition: "Mild", waterTemp: 21 },
    5: { temp: 17, condition: "Cool", waterTemp: 19 },
    6: { temp: 15, condition: "Cool", waterTemp: 17 },
    7: { temp: 14, condition: "Cool", waterTemp: 16 },
    8: { temp: 15, condition: "Cool", waterTemp: 16 },
    9: { temp: 18, condition: "Mild", waterTemp: 17 },
    10: { temp: 21, condition: "Mild", waterTemp: 18 },
    11: { temp: 23, condition: "Warm", waterTemp: 20 },
    12: { temp: 25, condition: "Hot", waterTemp: 22 },
  },
  "Melbourne": {
    1: { temp: 26, condition: "Hot", waterTemp: 20 },
    2: { temp: 26, condition: "Hot", waterTemp: 20 },
    3: { temp: 23, condition: "Mild", waterTemp: 18 },
    4: { temp: 19, condition: "Mild", waterTemp: 16 },
    5: { temp: 15, condition: "Cool", waterTemp: 14 },
    6: { temp: 12, condition: "Cool & Wet", waterTemp: 12 },
    7: { temp: 11, condition: "Cool & Wet", waterTemp: 11 },
    8: { temp: 12, condition: "Cool", waterTemp: 11 },
    9: { temp: 14, condition: "Mild", waterTemp: 12 },
    10: { temp: 18, condition: "Mild", waterTemp: 13 },
    11: { temp: 21, condition: "Warm", waterTemp: 15 },
    12: { temp: 24, condition: "Hot", waterTemp: 18 },
  },
  "Brisbane": {
    1: { temp: 29, condition: "Hot & Humid", waterTemp: 26 },
    2: { temp: 29, condition: "Hot & Humid", waterTemp: 26 },
    3: { temp: 27, condition: "Humid", waterTemp: 25 },
    4: { temp: 24, condition: "Mild", waterTemp: 23 },
    5: { temp: 21, condition: "Mild", waterTemp: 21 },
    6: { temp: 18, condition: "Cool", waterTemp: 19 },
    7: { temp: 17, condition: "Cool", waterTemp: 18 },
    8: { temp: 18, condition: "Cool", waterTemp: 18 },
    9: { temp: 21, condition: "Mild", waterTemp: 20 },
    10: { temp: 24, condition: "Mild", waterTemp: 21 },
    11: { temp: 26, condition: "Warm", waterTemp: 23 },
    12: { temp: 28, condition: "Hot", waterTemp: 25 },
  },
  "Gold Coast": {
    1: { temp: 29, condition: "Hot & Humid", waterTemp: 26 },
    2: { temp: 29, condition: "Hot & Humid", waterTemp: 26 },
    3: { temp: 28, condition: "Humid", waterTemp: 25 },
    4: { temp: 25, condition: "Mild", waterTemp: 23 },
    5: { temp: 22, condition: "Mild", waterTemp: 21 },
    6: { temp: 19, condition: "Cool", waterTemp: 19 },
    7: { temp: 18, condition: "Cool", waterTemp: 18 },
    8: { temp: 18, condition: "Cool", waterTemp: 18 },
    9: { temp: 21, condition: "Mild", waterTemp: 20 },
    10: { temp: 24, condition: "Mild", waterTemp: 21 },
    11: { temp: 26, condition: "Warm", waterTemp: 23 },
    12: { temp: 28, condition: "Hot", waterTemp: 25 },
  },
  "Cairns": {
    1: { temp: 31, condition: "Hot & Wet", waterTemp: 29 },
    2: { temp: 31, condition: "Hot & Wet", waterTemp: 29 },
    3: { temp: 30, condition: "Hot & Wet", waterTemp: 29 },
    4: { temp: 29, condition: "Humid", waterTemp: 28 },
    5: { temp: 27, condition: "Dry", waterTemp: 26 },
    6: { temp: 25, condition: "Dry", waterTemp: 24 },
    7: { temp: 24, condition: "Dry", waterTemp: 23 },
    8: { temp: 25, condition: "Dry", waterTemp: 24 },
    9: { temp: 27, condition: "Dry", waterTemp: 25 },
    10: { temp: 29, condition: "Humid", waterTemp: 27 },
    11: { temp: 31, condition: "Hot & Humid", waterTemp: 28 },
    12: { temp: 31, condition: "Hot & Wet", waterTemp: 29 },
  },
  "Perth": {
    1: { temp: 31, condition: "Hot", waterTemp: 22 },
    2: { temp: 31, condition: "Hot", waterTemp: 22 },
    3: { temp: 28, condition: "Hot", waterTemp: 22 },
    4: { temp: 24, condition: "Mild", waterTemp: 21 },
    5: { temp: 19, condition: "Mild", waterTemp: 19 },
    6: { temp: 16, condition: "Cool & Wet", waterTemp: 17 },
    7: { temp: 15, condition: "Cool & Wet", waterTemp: 16 },
    8: { temp: 16, condition: "Cool", waterTemp: 16 },
    9: { temp: 18, condition: "Mild", waterTemp: 17 },
    10: { temp: 22, condition: "Warm", waterTemp: 18 },
    11: { temp: 26, condition: "Warm", waterTemp: 19 },
    12: { temp: 29, condition: "Hot", waterTemp: 21 },
  },
};

// Parse month number from date string like "Jan 12, 2026" or "Nov 30, 2026"
export function parseMonth(dateStr: string): number {
  const months: Record<string, number> = {
    jan: 1, feb: 2, mar: 3, apr: 4, may: 5, jun: 6,
    jul: 7, aug: 8, sep: 9, oct: 10, nov: 11, dec: 12,
  };
  const m = dateStr.toLowerCase().match(/^([a-z]{3})/);
  return m ? (months[m[1]] ?? 0) : 0;
}

// Get weather for a race given its city and date string
export function getRaceWeather(location: string, dateStr: string): WeatherInfo | null {
  const city = location.split(",")[0].trim();
  const month = parseMonth(dateStr);
  if (!month) return null;
  const cityData = CITY_WEATHER[city];
  if (!cityData) return null;
  return cityData[month] ?? null;
}
