import { db } from "./storage.js";
import { exploreSites } from "../shared/schema.js";

export async function seedExplore() {
  const data = [
    // India
    { name: "Rajasthan: Jaipur, Jodhpur & Jaisalmer", country: "India", region: "Rajasthan", category: "Cities", description: "The Pink and Blue cities — Amber Fort, Mehrangarh, royal palaces, and the Thar Desert on the edge of town.", bestMonths: "Oct—Mar", url: "https://www.tourism.rajasthan.gov.in", emoji: "🏰", lat: "26.9124", lng: "75.7873" },
    { name: "Hampi Ruins", country: "India", region: "Karnataka", category: "Temples", description: "Boulder-strewn landscape with 600-year-old Vijayanagara Empire temples. Surreal, other-worldly, and largely undiscovered.", bestMonths: "Oct—Feb", url: "https://en.wikipedia.org/wiki/Hampi", emoji: "🛕", lat: "15.3350", lng: "76.4600" },
    { name: "Rishikesh & Haridwar", country: "India", region: "Uttarakhand", category: "Mountains", description: "Yoga capital of the world. Ganges rafting, Himalayan trekking trailhead, and the nightly Ganga Aarti ceremony.", bestMonths: "Mar—Jun, Sep—Nov", url: "https://en.wikipedia.org/wiki/Rishikesh", emoji: "⛰️", lat: "30.1083", lng: "78.2972" },
    { name: "Andaman & Nicobar Islands", country: "India", region: "Andaman Sea", category: "Islands", description: "Crystal-clear water, pristine coral reefs. Radhanagar Beach is Asia's best. Exceptional snorkelling and diving.", bestMonths: "Nov—May", url: "https://en.wikipedia.org/wiki/Andaman_and_Nicobar_Islands", emoji: "🏝️", lat: "11.7401", lng: "92.6586" },
    { name: "Kerala Backwaters", country: "India", region: "Kerala", category: "Nature", description: "Houseboat journey through a labyrinth of lagoons, canals and rice paddies. Ayurvedic retreats and spice plantations.", bestMonths: "Sep—Mar", url: "https://en.wikipedia.org/wiki/Kerala_backwaters", emoji: "🌿", lat: "9.4981", lng: "76.3388" },
    { name: "Spiti Valley", country: "India", region: "Himachal Pradesh", category: "Mountains", description: "High-altitude cold desert at 4200m. Ancient Buddhist monasteries, snow leopard territory, stargazing heaven.", bestMonths: "Jun—Sep", url: "https://en.wikipedia.org/wiki/Spiti", emoji: "🏔️", lat: "32.2269", lng: "78.0718" },
    // Japan
    { name: "Kyoto: Temples & Geisha Districts", country: "Japan", region: "Kansai", category: "Temples", description: "Fushimi Inari's 10,000 torii gates, Arashiyama bamboo forest, and Gion's preserved geisha culture.", bestMonths: "Mar—May, Oct—Nov", url: "https://en.wikipedia.org/wiki/Kyoto", emoji: "⛩️", lat: "35.0116", lng: "135.7681" },
    { name: "Japanese Alps Traverse", country: "Japan", region: "Chubu", category: "Mountains", description: "Kamikochi valley, Tateyama Kurobe Alpine Route, and onsen towns like Shirahone. World-class trekking.", bestMonths: "Jul—Oct", url: "https://en.wikipedia.org/wiki/Japanese_Alps", emoji: "🏔️", lat: "36.2048", lng: "137.6720" },
    { name: "Okinawa Islands", country: "Japan", region: "Okinawa", category: "Islands", description: "Subtropical paradise: ancient Ryukyu castles, pristine coral, and the world's longest-lived people.", bestMonths: "May—Jul, Oct—Nov", url: "https://en.wikipedia.org/wiki/Okinawa_Islands", emoji: "🏝️", lat: "26.5013", lng: "127.9454" },
    { name: "Hokkaido: Wildlands & Powder", country: "Japan", region: "Hokkaido", category: "Nature", description: "Daisetsuzan national park, Shiretoko UNESCO wilderness, and Niseko ski fields. Untouched Japan.", bestMonths: "Jun—Sep, Jan—Feb", url: "https://en.wikipedia.org/wiki/Hokkaido", emoji: "🌲", lat: "43.0618", lng: "141.3545" },
    // Thailand
    { name: "Chiang Mai: Temples & Jungle", country: "Thailand", region: "Northern Thailand", category: "Temples", description: "300+ temples, elephant sanctuaries, night bazaars and jungle trekking from the city. Cultural heart of Thailand.", bestMonths: "Nov—Feb", url: "https://en.wikipedia.org/wiki/Chiang_Mai", emoji: "🛕", lat: "18.7883", lng: "98.9853" },
    { name: "Koh Lanta & Krabi Islands", country: "Thailand", region: "Andaman Coast", category: "Islands", description: "Railay Beach only accessible by boat, sea kayaking through limestone karsts, and world-class diving.", bestMonths: "Nov—Apr", url: "https://en.wikipedia.org/wiki/Ko_Lanta_Yai", emoji: "🏝️", lat: "7.6079", lng: "99.0477" },
    { name: "Pai & Mae Hong Son Loop", country: "Thailand", region: "Northern Thailand", category: "Mountains", description: "Misty mountain valley, hot springs, bamboo bridges and a 762-curve mountain road. Thailand's best-kept secret.", bestMonths: "Nov—Feb", url: "https://en.wikipedia.org/wiki/Pai,_Thailand", emoji: "⛰️", lat: "19.3578", lng: "98.4420" },
    // Vietnam
    { name: "Ha Long Bay & Lan Ha Bay", country: "Vietnam", region: "Northeast", category: "Nature", description: "2000 limestone karst islands rising from emerald water. Kayak through caves, sleep on a junk boat.", bestMonths: "Apr—Jun, Sep—Nov", url: "https://en.wikipedia.org/wiki/H%E1%BA%A1_Long_Bay", emoji: "🌊", lat: "20.9101", lng: "107.1839" },
    { name: "Hội An Ancient Town", country: "Vietnam", region: "Central Vietnam", category: "Cities", description: "UNESCO-listed trading port frozen in time. Lantern-lit streets, master tailors, river boat rides.", bestMonths: "Feb—Jul", url: "https://en.wikipedia.org/wiki/H%E1%BB%99i_An", emoji: "🏮", lat: "15.8801", lng: "108.3380" },
    { name: "Sapa & Fansipan", country: "Vietnam", region: "Northwest", category: "Mountains", description: "Terraced rice fields of the Hmong and Dao peoples. Trek to Indochina's highest peak at 3143m.", bestMonths: "Mar—May, Sep—Nov", url: "https://en.wikipedia.org/wiki/Sa_Pa,_L%C3%A0o_Cai", emoji: "🏔️", lat: "22.3364", lng: "103.8438" },
    // Philippines
    { name: "El Nido & Bacuit Archipelago", country: "Philippines", region: "Palawan", category: "Islands", description: "Hidden lagoons, white sand beaches and dramatic limestone cliffs. Consistently ranked world's best island.", bestMonths: "Dec—May", url: "https://en.wikipedia.org/wiki/El_Nido,_Palawan", emoji: "🏝️", lat: "11.1784", lng: "119.3973" },
    { name: "Banaue Rice Terraces", country: "Philippines", region: "Ifugao", category: "Mountains", description: "2000-year-old Ifugao rice terraces carved into mountain slopes — the 8th wonder of the world.", bestMonths: "Dec—May", url: "https://en.wikipedia.org/wiki/Banaue_Rice_Terraces", emoji: "🌾", lat: "16.9187", lng: "121.0607" },
    // Indonesia
    { name: "Bali: Temples, Rice & Volcanoes", country: "Indonesia", region: "Bali", category: "Nature", description: "Tegalalang rice terraces, Uluwatu cliff temple at sunset, sunrise hike on Mt Batur, and world-class surf.", bestMonths: "May—Sep", url: "https://en.wikipedia.org/wiki/Bali", emoji: "🌋", lat: "-8.3405", lng: "115.0920" },
    { name: "Komodo National Park", country: "Indonesia", region: "East Nusa Tenggara", category: "Nature", description: "Trek alongside Komodo dragons, world-class diving at Manta Point, and Pink Beach.", bestMonths: "Apr—Dec", url: "https://en.wikipedia.org/wiki/Komodo_National_Park", emoji: "🦎", lat: "-8.5500", lng: "119.4900" },
    { name: "Raja Ampat Islands", country: "Indonesia", region: "West Papua", category: "Islands", description: "Marine biodiversity capital of the world. Above water: dramatic karst islands. Below: 75% of all coral species.", bestMonths: "Oct—Apr", url: "https://en.wikipedia.org/wiki/Raja_Ampat_Islands", emoji: "🐠", lat: "-0.2300", lng: "130.5220" },
    // Nepal
    { name: "Everest Base Camp Trek", country: "Nepal", region: "Khumbu", category: "Mountains", description: "The world's most iconic trek. Sherpas, Namche Bazaar, Tengboche monastery and views of 8000m peaks.", bestMonths: "Mar—May, Oct—Nov", url: "https://en.wikipedia.org/wiki/Everest_base_camps", emoji: "🏔️", lat: "27.9881", lng: "86.9250" },
    { name: "Annapurna Circuit", country: "Nepal", region: "Gandaki", category: "Mountains", description: "16-day circumnavigation of an 8000m massif. Thorong La pass at 5416m, Mustang's arid Tibetan plateau.", bestMonths: "Mar—May, Oct—Nov", url: "https://en.wikipedia.org/wiki/Annapurna_Circuit", emoji: "⛰️", lat: "28.5971", lng: "83.8201" },
    // Sri Lanka
    { name: "Sigiriya & Cultural Triangle", country: "Sri Lanka", region: "Central Province", category: "Temples", description: "5th-century Lion Rock fortress with frescoes, Dambulla cave temples and ancient Polonnaruwa city.", bestMonths: "Dec—Apr", url: "https://en.wikipedia.org/wiki/Sigiriya", emoji: "🦁", lat: "7.9570", lng: "80.7603" },
    { name: "Yala National Park", country: "Sri Lanka", region: "Southern Province", category: "Nature", description: "Highest density of leopards anywhere on earth. Elephants, sloth bears, and crocodiles in dry scrubland.", bestMonths: "Feb—Jul", url: "https://en.wikipedia.org/wiki/Yala_National_Park", emoji: "🐆", lat: "6.3728", lng: "81.5200" },
    // Malaysia
    { name: "Borneo: Kinabalu & Rainforest", country: "Malaysia", region: "Sabah", category: "Mountains", description: "Summit Southeast Asia's highest peak at 4095m. Sepilok orangutan sanctuary and Kinabatangan river.", bestMonths: "Mar—Apr, Jul—Sep", url: "https://en.wikipedia.org/wiki/Kinabalu_Park", emoji: "🦧", lat: "6.0750", lng: "116.5580" },
    { name: "George Town Penang", country: "Malaysia", region: "Penang", category: "Cities", description: "UNESCO street art city, Peranakan shophouses, best street food in Asia. British colonial heritage meets Chinese culture.", bestMonths: "Dec—Feb", url: "https://en.wikipedia.org/wiki/George_Town,_Penang", emoji: "🎨", lat: "5.4164", lng: "100.3327" },
    // Maldives
    { name: "Maldives: North Malé Atoll", country: "Maldives", region: "North Malé Atoll", category: "Islands", description: "Overwater bungalows, bioluminescent beaches, whale shark encounters, and the world's flattest nation.", bestMonths: "Nov—Apr", url: "https://en.wikipedia.org/wiki/North_Male_Atoll", emoji: "🌊", lat: "4.1755", lng: "73.5093" },
    // Cambodia
    { name: "Angkor Wat Archaeological Park", country: "Cambodia", region: "Siem Reap", category: "Temples", description: "Largest religious monument on earth. Pre-dawn entrance for the iconic sunrise reflection. Ta Prohm eaten by jungle.", bestMonths: "Nov—Mar", url: "https://en.wikipedia.org/wiki/Angkor_Wat", emoji: "🛕", lat: "13.4125", lng: "103.8670" },
    // Myanmar
    { name: "Bagan Temple Plains", country: "Myanmar", region: "Mandalay Region", category: "Temples", description: "Over 2000 temples across a vast plain. E-bike at sunset, hot air balloon at dawn.", bestMonths: "Nov—Feb", url: "https://en.wikipedia.org/wiki/Bagan", emoji: "🏛️", lat: "21.1717", lng: "94.8585" },
    // Jordan
    { name: "Petra: The Rose City", country: "Jordan", region: "Ma'an", category: "Temples", description: "Nabataean rock-carved city revealed through the Siq canyon. Treasury, Monastery, 800 monuments in rose-red sandstone.", bestMonths: "Mar—May, Sep—Nov", url: "https://en.wikipedia.org/wiki/Petra", emoji: "🏺", lat: "30.3285", lng: "35.4444" },
    { name: "Wadi Rum Desert", country: "Jordan", region: "Aqaba", category: "Nature", description: "Mars on earth. Sandstone arches, Bedouin camps, jeep safaris, and a sky with zero light pollution.", bestMonths: "Mar—May, Sep—Nov", url: "https://en.wikipedia.org/wiki/Wadi_Rum", emoji: "🏜️", lat: "29.5832", lng: "35.4200" },
    // South Korea
    { name: "Jeju Island", country: "South Korea", region: "Jeju Province", category: "Islands", description: "Haenyeo women free-divers, Hallasan volcanic crater, lava tube caves, and black sand beaches.", bestMonths: "Apr—Jun, Sep—Nov", url: "https://en.wikipedia.org/wiki/Jeju_Island", emoji: "🌋", lat: "33.4996", lng: "126.5312" },
    { name: "Seoul: Palaces & Night Markets", country: "South Korea", region: "Seoul", category: "Cities", description: "Gyeongbokgung palace, Bukchon hanok village, Hongdae nightlife and the world's best street food market at Gwangjang.", bestMonths: "Apr—May, Sep—Oct", url: "https://en.wikipedia.org/wiki/Seoul", emoji: "🏯", lat: "37.5665", lng: "126.9780" },
    // Taiwan
    { name: "Taiwan: Sun Moon Lake & Taroko", country: "Taiwan", region: "Central Taiwan", category: "Nature", description: "Cycling around a glacial lake, marble gorge hiking in Taroko, and night markets in Taichung.", bestMonths: "Oct—Apr", url: "https://en.wikipedia.org/wiki/Sun_Moon_Lake", emoji: "🦋", lat: "23.8656", lng: "120.9163" },
    // Bhutan
    { name: "Bhutan: Tiger's Nest & Haa Valley", country: "Bhutan", region: "Paro & Haa", category: "Mountains", description: "Paro Taktsang monastery clinging to a 900m cliff, pristine valleys and the world's only carbon-negative country.", bestMonths: "Mar—May, Sep—Nov", url: "https://en.wikipedia.org/wiki/Paro_Taktsang", emoji: "🐯", lat: "27.4919", lng: "89.3635" },
    // Laos
    { name: "Luang Prabang", country: "Laos", region: "Luang Prabang Province", category: "Temples", description: "UNESCO world heritage town at the confluence of the Mekong and Nam Khan. Monk alms at dawn, Kuang Si waterfall.", bestMonths: "Nov—Mar", url: "https://en.wikipedia.org/wiki/Luang_Prabang", emoji: "🏛️", lat: "19.8845", lng: "102.1348" },
    // Vietnam extras
    { name: "Phú Quốc Island", country: "Vietnam", region: "Kiên Giang", category: "Islands", description: "Vietnam's largest island — white sand, pepper plantations, fish sauce factories and some of the best sunsets in Asia.", bestMonths: "Nov—Apr", url: "https://en.wikipedia.org/wiki/Phu_Quoc", emoji: "🏖️", lat: "10.2898", lng: "103.9840" },
    // Additional Beaches
    { name: "Gili Islands", country: "Indonesia", region: "Lombok", category: "Islands", description: "Three tiny islands with zero motorised vehicles — bikes, horses, sea turtles and hammocks over the water.", bestMonths: "May—Sep", url: "https://en.wikipedia.org/wiki/Gili_Islands", emoji: "🐢", lat: "-8.3535", lng: "116.0387" },
    { name: "Koh Rong Sanloem", country: "Cambodia", region: "Preah Sihanouk", category: "Islands", description: "Bioluminescent plankton at night, empty white sand beaches by day. One of Southeast Asia's last undiscovered islands.", bestMonths: "Nov—May", url: "https://en.wikipedia.org/wiki/Koh_Rong_Sanloem", emoji: "✨", lat: "10.6167", lng: "103.2667" },
  ];

  for (const site of data) {
    db.insert(exploreSites).values(site).run();
  }
  console.log(`Seeded ${data.length} explore sites`);
}
